InteropIO/finsemble-seed

gulpfile.js, node_fileserver/FinsembleConfigs.js, src/components/assets/css/finsemble-overrides.scss, src/components/assets/sass/_colorPalette.scss, src/components/assets/sass/_dialogs.scss, src/components/assets/sass/_formElements.scss, src/components/assets/sass/_globals.scss, src/components/assets/sass/_menus.scss, src/components/assets/sass/_toolbar.scss, src/components/assets/sass/_variables.scss, src/components/assets/sass/_variablesDialogs.scss, src/components/assets/sass/_variablesMenus.scss, src/components/assets/sass/_variablesToolbar.scss, src/components/assets/sass/_variablesWindowFrame.scss, src/components/assets/sass/_variablesWindowManager.scss, src/components/assets/sass/_windowFrame.scss, src/components/assets/sass/_windowManager.scss, src/components/assets/sass/_workspaceManagement.scss
Merge in after we get white labeling in to the core (next week)
=> White labeling

gulpfile.js, package-lock.json, package.json
Simplified and organized the gulpfile which will make life easier for the project reorg
=> Gulpfile cleanup

build/webpack/webpack.files.js, build/webpack/webpack.services.js
small webpack addition to ensure CLI generated service client are built
=> webpack additions to build generated webservice clients

configs/application/config.json, gulpfile.js, server/server-extensions.md, server/server.js
Adds the ability to extend the server functionality via an optional _server-extensions.js_ file. This allows users to extend the server functionality without having to edit the files we provide.
=> Server extensions

configs/application/config.json, gulpfile-extensions.md, gulpfile.js
Added the ability to modify/extend the gulpfile without editing _gulpfile.js_.
=> Gulpfile extension

build/webpack/defaultWebpackConfig.js, build/webpack/webpack.files.js, configs/other/server-environment-startup.json, gulpfile-extensions.md, gulpfile.js, package-lock.json, package.json, server/FinsembleConfigs.js, server/server.js
toolbar down to ~0.5 MB from ~2 MB
=> Add minify

build/webpack/defaultWebpackConfig.js, package.json
Check whether NODE_ENV is production before adding uglify plug-in
Added script to explicitly build in production and development
Dev build is ~60MB (full dist)
Prod build is ~7BM (full dist)
=> Only minify in production

src-built-in/components/appLauncher/src/stores/appLauncherStore.js, src-built-in/components/assets/css/_dialogs.css, src-built-in/components/assets/css/_formElements.css, src-built-in/components/assets/css/finsemble.css
The dialogs are by no means styled or standardized, but they're no longer as janky looking. Adhoc component dialog is fixed, as well as hover states.
=> Dialog fixes

configs/application/config.json, src-built-in/components/adhocComponentForm/adhocComponentForm.html, src-built-in/components/appCatalog/appCatalog.html, src-built-in/components/appLauncher/appLauncher.html, src-built-in/components/authentication/defaultAuthentication.html, src-built-in/components/dockingGroupMask/dockingGroupMask.html, src-built-in/components/fileMenu/fileMenu.html, src-built-in/components/searchMenu/searchMenu.html, src-built-in/components/welcome/welcome.html, tutorials/accountDetail/accountDetail.html, tutorials/accountList/accountList.html, tutorials/accountStatement/accountStatement.html
This PR is to remove and clean up config items in the seed that are no longer relevant.
=> Config deprecation

build/webpack/webpack.components.js, build/webpack/webpack.finsemble-built-in.entries.json, configs/application/presentationComponents.json, src-built-in/components/userPreferences/UserPreferences.html, src-built-in/components/userPreferences/src/app.jsx, src-built-in/components/yesNoDialog/YesNoDialog.html
A few fixes from recent support calls.
=> 2.4.1 fixes

src-built-in/components/toolbar/stores/toolbarStore.js
CTRL+SHIFT+DOWN and up are excel hotkeys. Change our minimize/BTF hotkeys to ctrl+alt+down
=> Minimize hotkeys6590

src-built-in/components/appLauncher/src/components/componentItem.jsx, src-built-in/components/floatingTitlebar/src/app.jsx, src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx, src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
dragging/dropping from c# is text/plain. text/json results in null data. So replacing all text/json with text/plain.
=> c# is unable to get text/json

src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx, src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
Must be used with group-breaks branch of finsemble. 
See https://github.com/ChartIQ/finsemble/pull/772
Details: https://chartiq.kanbanize.com/ctrl_board/18/cards/7556/details
=> Small Window Group Fixes

src-built-in/adapters/localStorageAdapter.js, src-built-in/components/appCatalog/src/app.jsx, src-built-in/components/appCatalog/src/components/App.jsx, src-built-in/components/appCatalog/src/components/AppContent.jsx, src-built-in/components/appCatalog/src/components/AppDetails.jsx, src-built-in/components/appCatalog/src/stores/searchStore.js, src-built-in/components/appLauncher/src/app.jsx, src-built-in/components/appLauncher/src/components/componentItem.jsx, src-built-in/components/fileMenu/src/stores/fileMenuStore.js, src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx, src-built-in/components/floatingTitlebar/src/stores/headerStore.js, src-built-in/components/processMonitor/src/app.jsx, src-built-in/components/searchMenu/src/app.jsx, src-built-in/components/searchMenu/src/stores/searchStore.js, src-built-in/components/toolbar/components/Chat.jsx, src-built-in/components/toolbar/src/dynamicToolbar.jsx, src-built-in/components/toolbar/stores/searchStore.js, src-built-in/components/toolbar/stores/toolbarStore.js, src-built-in/components/userPreferences/src/components/content/Workspaces.jsx, src-built-in/components/userPreferences/src/stores/UserPreferencesStore.jsx, src-built-in/components/welcome/welcome.js, src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx, src-built-in/components/windowTitleBar/src/components/left/LinkerButton.jsx, src-built-in/components/windowTitleBar/src/components/left/LinkerGroups.jsx, src-built-in/components/windowTitleBar/src/components/right/MaximizeButton.jsx, src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js, src-built-in/components/windowTitleBar/src/windowTitleBar.jsx, src-built-in/components/workspaceManagementMenu/src/app.jsx, src-built-in/components/workspaceManagementMenu/src/components/workspaceList.jsx
Remove console logs throughout the seed to clean up the consoles.
=> Remove console logs

src-built-in/components/windowTitleBar/src/components/center/logo.jsx, src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js, src-built-in/components/windowTitleBar/src/windowTitleBar.jsx
Resolves issues with the onTitleChange event handler that was throwing errors.
=> Fix on title change

src-built-in/components/windowTitleBar/src/windowTitleBar.jsx
See card for details:
https://chartiq.kanbanize.com/ctrl_board/18/cards/8117/details
=> 8117 Title change bug 

src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx, src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
This prevents images from being loaded if dropped on the tab region.
=> PreventDefault in the tab region. 

build/webpack/webpack.components.js
This was causing an issue in some buids for Citadel.
=> Added check to not accidentally create a folder called .gitignore

src-built-in/components/toolbar/stores/toolbarStore.js
Changes the key combo for search
=> Changes key command for search to Ctrl + Alt + F

build/webpack/webpack.adapters.entries.json, configs/application/config.json, package.json, src-built-in/adapters/indexDBAdapter.js
I think this resolves all of the issues I raised from my review. Sadly I wasn't able to make it an ES6 class because of a weird error where `setBaseName` was undefined. Should probably figure out why that is, and fix it in BaseStorage.
=> Index db adapter cleanup

src-built-in/adapters/indexedDBAdapter.js
The schema version caused the adapter to fail for me, so I removed it. I fixed the issues style issues I saw, and restructures to be a bit more class like, collecting the interface methods together. Some of the methods are still missing documentation for the parameters, but I think those are interface methods.
=> Index db adapter cleanup 2

src-built-in/components/appCatalog/src/stores/searchStore.js, src-built-in/components/complexMenu/ComplexMenu.jsx
We hardcoded a c into the catalog store. I just removed that. This also requires a fix on the FInsemble side.
=> #9212 fix for search in catalog

src-built-in/adapters/indexedDBAdapter.js
Implemented simple queuing for indexedDBAdapter to capture storage requests prior to initialization, and service them immediately when initialization is complete.
=> 9324 IndexedDBAdapter Queuing

configs/openfin/manifest-local.json
Manifest file updated to use Assimilation 2.0.3
=> Set Assimilation asset version 2.0.3 (#9195)

.editorconfig, .github/PULL_REQUEST_TEMPLATE.md
**Changes**
- Add a .editorconfig file to define the team's coding styles between different editors and IDEs.
- Add a customizable github pull requests template.
=> Create .editorconfig file to define the team's coding styles between different editors and IDEs.

src-built-in/adapters/indexedDBAdapter.js, src-built-in/adapters/localStorageAdapter.js
The keys function was returning the keys with the key preface, but all of the other functions add the key preface in, which meant that the key could not be found. I change the keys function to return the finsemble key, so now when the other functions add the Finsemble, the user and the topic, the item in local storage will be found.
=> Local storage fixes

src-built-in/components/authentication/defaultAuthentication.html, src-built-in/components/dockingGroupMask/dockingGroupMask.html, src-built-in/components/inputAndSelectionDialog/inputAndSelectionDialog.html, src-built-in/components/linker/linker.html, src-built-in/components/notification/notification.html, src-built-in/components/processMonitor/processMonitor.html, src-built-in/components/singleInputDialog/singleInputDialog.html, src-built-in/components/system/blankComponent/index.html, src-built-in/components/toolbar/toolbar.html, src-built-in/components/userPreferences/userPreferences.html, src-built-in/components/workspaceManagementMenu/workspaceManagementMenu.html, src-built-in/components/yesNoDialog/yesNoDialog.html
A customer reported issues with invalid HTML, and suggested we add linters to catch this. I did a pass on the HTML to find and fix errors. I will add the linter to the build in a separate PR
=> HTML fixes

assets/css/_windowTitleBar.css, src-built-in/components/windowTitleBar/src/components/HoverDetector.jsx, src-built-in/components/windowTitleBar/src/components/left/LinkerButton.jsx, src-built-in/components/windowTitleBar/src/components/right/CloseButton.jsx
=> 9490 intelligent hover detector

configs/application/presentationComponents.json
**Resolves #001**
- Change A
- Change B
- Step 1
- Step 2
=> Toolbar config normalization

src-built-in/components/common/windowTitle.jsx, src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx, src-built-in/components/floatingTitlebar/src/components/tab.jsx, src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx, src-built-in/components/windowTitleBar/src/components/center/tab.jsx, src-built-in/components/windowTitleBar/src/components/center/title.jsx
**Resolves 9879**
- Adds a title component that receives a windowIdentifier. The component uses the identifier to wrap the window, retrieve the options for that window, and set the title.
- titles change for windows. It should be visible in all windows in the stack.
=> 9879 title changes

src-built-in/components/common/windowTitle.jsx, src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx, src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
Fixes title width issues when there aren't tabs.
=> 9970 Don't set tabWidth on the title.

src-built-in/components/windowTitleBar/src/components/left/LinkerButton.jsx
**Resolves 10023**
- proper parent for calculating offsets
- Linker Position should be correct. Open several windows and see that linker is in proper position
=> 10023 Fix linkerWindow positioning

assets/css/_theme.css, src-built-in/components/appLauncher2/src/index.jsx, src-built-in/components/appLauncher2/style.css, src-built-in/components/appMarket/appMarket.css, src-built-in/components/shared/style.css
Themed and variable-tized the appMenu, amongst other minor CSS fixes. Also pruned unused CSS copied over from complex-menu.
https://chartiq.kanbanize.com/ctrl_board/18/cards/9684/details
https://chartiq.kanbanize.com/ctrl_board/18/cards/9562/details
=> 9684 & 9562 css fixes

src-built-in/components/appLauncher2/src/components/AppActionsMenu.jsx, src-built-in/components/appLauncher2/src/components/AppTagsList.jsx, src-built-in/components/appLauncher2/src/components/Content.jsx, src-built-in/components/appLauncher2/src/components/FolderActionsMenu.jsx, src-built-in/components/appLauncher2/src/components/FoldersList.jsx, src-built-in/components/appLauncher2/src/stores/StoreActions.js, src-built-in/components/appLauncher2/style.css, src-built-in/components/appMarket/appMarket.css, src-built-in/components/appMarket/src/components/AppCard.jsx, src-built-in/components/appMarket/src/components/Hero.jsx
- Addresses fixes/bugs here https://chartiq.kanbanize.com/ctrl_board/18/cards/10202/subtasks
=> Fixes to address most bugs in 10202

assets/css/_theme.css, src-built-in/components/appCatalog2/appCatalog.css, src-built-in/components/appCatalog2/src/app.jsx, src-built-in/components/appCatalog2/src/components/AppResults.jsx, src-built-in/components/appCatalog2/src/components/Carousel.jsx, src-built-in/components/appCatalog2/src/components/Home.jsx, src-built-in/components/appCatalog2/src/components/SearchBar.jsx, src-built-in/components/appCatalog2/src/stores/storeActions.js, src-built-in/components/appLauncher2/src/components/FilterSort.jsx, src-built-in/components/appLauncher2/style.css, src-built-in/components/shared/TagsMenu.jsx, src-built-in/components/shared/style.css, src-built-in/components/toolbar/components/Search.jsx
**Resolves issue [10202](https://chartiq.kanbanize.com/ctrl_board/18/cards/10202/subtasks)**
-Fixes bugs mentioned in 10202 subtasks.
-Specifically addresses open/remove buttons, carousel operability, and tag search to be AND instead of OR
- Addresses all checked subtasks from 10202
=> [AppCatalog] 10202 final mvp bug fixes

src-built-in/components/appLauncher2/src/utils/sort-functions.js
**Resolves #10386**
- Created a favorites sorter in sort-functions.js
- Add 2 or more apps to favorites
- Next to sort by click on "Favorites"
The apps should be sorted by Favorites, in a descending order
=> [AppLauncher] sort by favorites

assets/css/_menus.css, assets/css/_theme.css, configs/application/presentationComponents.json, src-built-in/components/appCatalog2/appCatalog.css, src-built-in/components/appLauncher/src/components/componentItem.jsx, src-built-in/components/appLauncher2/src/components/AppActionsMenu.jsx, src-built-in/components/appLauncher2/src/components/FoldersList.jsx, src-built-in/components/appLauncher2/style.css, src-built-in/components/toolbar/config.json, src-built-in/components/workspaceManagementMenu/src/components/workspace.jsx, src-built-in/components/workspaceManagementMenu/src/components/workspaceList.jsx
**Resolve issue [10383](https://chartiq.kanbanize.com/ctrl_board/18/cards/10383/details)**
- Restored text truncation in the appLauncher
- Changed pin icons to ff-favorite (stars) to reflect consistency with new appLauncher. Adjusted some hover-states for further consistency.
- Put in a large amount of text anywhere in the appLauncher. Text should not inappropriately overflow or stretch the interface.
- Check workspace menu for star icons instead of pins. Make sure they possess hover states.
=> [App Launcher] Text and Icons

build/webpack/webpack.finsemble-built-in.entries.json, configs/application/components.json, configs/application/config.json, src-built-in/components/nonConfiguredComponent/nonConfiguredComponent.css, src-built-in/components/nonConfiguredComponent/nonConfiguredComponent.html, src-built-in/components/nonConfiguredComponent/nonConfiguredComponent.js
**Resolves issue [10620](https://chartiq.kanbanize.com/ctrl_board/18/cards/10620/details)**
- Added a config for choosing what component to spawn if one isn't found in the launcher service
-Look at core PR with the same name
=> added a config for unknnow components.

build/webpack/webpack.adapters.entries.json, configs/application/config.json, src/adapters/badIndexedDBAdapter.js
**Resolves issue [####](https://chartiq.kanbanize.com/ctrl_board/18/cards/####/details)**
-Change 1
-Change 2
-How did you verify that your code satisfies the card's requirements?
=> Bad storage adapter

configs/application/presentationComponents.json
**Resolves issue [10045](https://chartiq.kanbanize.com/ctrl_board/18/cards/10045/details)**
-Removed duplicate config after diffing to see which one was correct.
-Ran finsemble. Opened notepad. Verified that the floater wasn't registered with docking and didn't have errors.
=> 10045 duplicate config

configs/application/config.json, configs/other/server-environment-startup.json, gulpfile.js
**Resolves issue [11024](https://chartiq.kanbanize.com/ctrl_board/18/cards/11024/details)**
- new channelAdapter for debugging
- I Can debug the main process!!
=> 11024 allow electron debugging

configs/application/composites.json, configs/application/config.json
**Resolves issue [#11421](https://chartiq.kanbanize.com/ctrl_board/18/cards/11421/details)**
- Create a new composites.json file
- Import composites.json in config.js
- Make sure that composites.json file exists
- Look for the file import entry in config.js
And finally
Run Finsemble seed and in chrome developer console run the following to see whether the composites entry exist in the config object
```
FSBL.Clients.ConfigClient.getValues(null, (error, data) => { 
console.log(data.finsemble.composites)
})
```
=> 11421 Create composites.json and import it in config.js

configs/application/components.json, configs/application/composites.json, src-built-in/components/composite-titlebar/index.html
**Resolves issue [#11426](https://chartiq.kanbanize.com/ctrl_board/18/cards/11426/details)**
- Create Composite Titlebar component
- modified composites.json
Please only test this branch with corresponding finsemble branch at https://github.com/ChartIQ/finsemble/pull/1111
=> [11426] composite spawning

configs/application/components.json, configs/application/composites.json, src-built-in/components/composite-titlebar/index.html
**Resolves issue [####](https://chartiq.kanbanize.com/ctrl_board/18/cards/####/details)**
-Change 1
-Change 2
-How did you verify that your code satisfies the card's requirements?
=> 11426 composite spawn

.github/PULL_REQUEST_TEMPLATE.md
chore: #id_no_card_for_this Update pull req template
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/no_card_for_this/details)
* Make better PR template
1. Talked.
2. Made this PR.
=> chore: #id_no_card_for_this Update pull req template

configs/application/config.json, configs/application/securityPolicies.json
**Resolves issue [12005](https://chartiq.kanbanize.com/ctrl_board/18/cards/12005/details)**
- Adds an example security policy definition to the seed.
- See PR in finsemble for a description of testing (https://github.com/ChartIQ/finsemble/pull/1164)
=> feat: #id 12005 Adds security policy definitions to seed

configs/application/securityPolicies.json
Reverts ChartIQ/finsemble-seed#335
=> Revert "Fixed naming and misspelling."

gulpfile-extensions-example.js, gulpfile.js
**Resolves issue [11789](https://chartiq.kanbanize.com/ctrl_board/18/cards/11789/details)**
Add example of customizing launchE2O and launch args into gulpfile-extensions.js. Add envOrArg to taskMethods.
App still launches, e2o included the flags specified in gulpfile-extensions `launchE2o`
=> 11789 e2o launch args

configs/openfin/manifest-local.json
**Resolves issue [10031](https://chartiq.kanbanize.com/ctrl_board/18/cards/10031/details)**
Upgrade openfin9 to latest version
Basic startup functionality.
=> 10031 upgrade openfin to latest version of 9

configs/application/config.json
fix: #id 12793
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12793/details)
removed dead config for splitting off services in there own process (which was misleading)
Ran finsemble -- everything should come up fine
=> 12793 separate router process

configs/openfin/manifest-local.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12898/details)
* Changed IAS.serverAddress to ws://127.0.0.1:3376
=> feat: #id [12898] default to 127.0.0.1

configs/application/securityPolicies.json
PR is only to reduce confusion.
=> Remove readRegistryValue. The functionality was never implemented

src-built-in/components/toolbar/stores/toolbarStore.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14098/details)
* The toolbar used to use setComponentState to save state, which it should not do because it is not part of the workspace.
* Use Storage instead of Workspace to save the data
1. Reset Finsemble
1. Move the toolbar
1. Restart Finsemble
1. [x] Toolbar should show up where you moved it
1. Dock the toolbar again
1. Restart Finsemble
1. [x] Toolbar should show up docked
=> fix: #id 14098 use storage instead of workspace to save toolbar state

src-built-in/components/fileMenu/src/stores/fileMenuStore.js, src-built-in/components/toolbar/stores/searchStore.js, src-built-in/components/toolbar/stores/toolbarStore.js
fix: #id 14490
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14490/details/)
1. Changed name of SystemManagerAPI to SystemManagerClient
_Use startup-tweaks branch of finsemble._
1. Start finsemble and confirm no errors in the system log
=> change SystemManagerAPI to SystemManagerClient

.editorconfig, configs/application/components.json, src-built-in/components/authentication/authentication.js
Fix built in defaultAuthentication initialisation.
fix: #id [14723]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/14723/details/)
1. Built in auth component to use FSBL on ready
2. Can now submit username and password using keypad enter too
3. editors no longer add trailing space to .json files
4. Login Window is now correct size.
Add to application/config.json
```
"authentication": {
"startup": {
"adapter": "PASSWORD",
"component": "defaultAuthentication"
}
}
````
Login window shows
=> Fix #14723 built in defaultAuthentication initialization.

package.json
For more information on what changed, please see https://documentation.chartiq.com/finsemble/changelog.html#3-10-1.
=> update versions of finsemble and react controls

configs/application/config.json
allow the hiding of title bars for native applications
feat: #id [14780]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14780/details)
This PR simply adds a servicesConfig->assimilation->hideTitleBars config item to the seed.  The accompanying PR in Finsemble has the code to handle this logic.
See the accompanying PR in Finsemble.
=> adding the config variable to hide floating title

configs/openfin/manifest-local.json
test: #15328 [15328]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15328/details)
* assimilation build update to PR50
https://github.com/ChartIQ/finsemble-assimilation/pull/50
=> 15328 secondary 1 scaling issue

configs/application/config.json
See https://github.com/ChartIQ/finsemble/pull/1528
=> remove undocumented config

configs/application/components.json
See [Finsemble PR](https://github.com/ChartIQ/finsemble/pull/1493)
=> 14725 alwaysOnTop config bad example

configs/other/installer.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15320/details)
* Added properties to _configs/other/config.json_
Test in conjunction with 9finsemble-electron-adapter PR](https://github.com/ChartIQ/finsemble-electron-adapter/pull/135).
=> feat: #id [15320] Added properties needed for signed installers

configs/openfin/manifest-local.json
fix: #id 15366
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15366/details/)
Enable FEA handshake in manifest. 
See FEA companion PR in ticket for description of testing.
=> add requireHandshake property to manifest

gulpfile.js
feat: #id [CARD]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/CARD/details)
* Update the path of FEA
Description of testing is described in [this ](https://github.com/ChartIQ/finsemble-electron-adapter/pull/134)PR
=> feat: #id 14871 setup webpack for building FEA main process

src/components/multiWindowAppExample/child-preload.js, src/components/multiWindowAppExample/child.html, src/components/multiWindowAppExample/index.html, src/components/multiWindowAppExample/parent-preload.js
Uses a `transmit` to broadcast. Next task is to use `query` to ensure 1:1 communication
=> Parent->child->parent communication POC

src-built-in/components/userPreferences/src/components/content/Workspaces.jsx
fix: #id 16780
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16780/details/)
* After discussing the issue with Brad, we decided to change the default option for "force" to be "false".
Detailed testing description is written [here](https://github.com/ChartIQ/finsemble/pull/1571)
=> fix: #id 16780 change 'force' flag to default to false

configs/application/components.json
docs: #id 12474
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12474/details)
* updated link to new seed project
=> docs: id 12474

README.md
docs: #id NA
* Updated outdated README
=> docs: #id NA

README.md
docs: #id 12474
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12474/details)
* Updated link to new getting started tutorial
=> docs: #id 12474

src-built-in/components/advancedAppCatalog/src/components/Toast.jsx
style: #id [19505]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19505/details)
Changed the text of the toast message per instructions in card.
Verified the text displays correctly in the toast message.
=> 19505 Change App Added/Removed Toast Text

src-built-in/components/welcome/welcome.js
docs: #id 12747
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12747/details)
* Changed link to new tutorial
=> docs: #id 12747

src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
Moved the logic into finsemble. See core for the PR.
=> fix: #id 14573 Taskbar Icon Disappears

assets/css/_toolbar.css, src-built-in/components/toolbar/src/app.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/21598/details)
Requires: https://github.com/ChartIQ/finsemble-ui/pull/6
* Paired with pr to finsemble-ui to wrap these components
* Adds the updated components to toolbar shell.
* Temporary solution for adding toolbar sections - will need to work with team to find a longterm solution.
=> feat: #id 21598 refactor RevealAll, MinimizeAll and AutoArrange

assets/css/_theme.css, assets/css/_toolbar.css
refactor: #id 22220 
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22220/details/)
* CSS for scroll button and delete button
1. Test this branch along with branch `22220-favorites-scrolling` for finsemble-ui repo
1. Launch finsemble and checkout the toolbar favorites scrolling indicator and close button
=> refactor: #id 22220 Favorites scrolling

src-built-in/components/yesNoDialog/README.md
Docs: #22818
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22818/details)
* Fixed name of parameters for yesNoDialog
1. Look at yesNoDialog component
2. Observe parameters
3. Look at documentation
4. Are they the same?
5. Give me a Brazos taco
=> Docs: #22818

configs/application/config.json
See PR in the core for more details.
https://chartiq.kanbanize.com/ctrl_board/48/cards/23647/details/
=> fix: #id 23647 Fix useFeaSpawn

src-built-in/components/advancedAppCatalog/appCatalog.css, src-built-in/components/advancedAppCatalog/src/components/Showcase/Header.jsx
style: #id [22246]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22246/details)
**Changed Remove from trash can to button**
1. Run Finsemble
1. Open Advanced App Catalog and add an App
1. On the detail page, verify that we have a "Remove" button where the Trash can was, and that it's styled correctly.
=> 22246 app catalog ui updates

src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
Reverts ChartIQ/finsemble-seed#624
=> Revert "fix: #id 22639 Don't add app to current custom folder"

build/webpack/webpack.finsemble-built-in.entries.json, configs/application/UIComponents.json, configs/application/config.json, src/components/systemTrayComponent/systemTrayComponent.html, src/components/systemTrayComponent/systemTrayComponent.jsx
* Adds a system tray component that imports the file menu's menu items.
1. Right clicked on the icon and saw it open.
2. Clicked a couple of buttons.
=> System-tray

package.json
Updated version in package.json
=> Updated version in package.json

package.json
Update version in package.json to 4.4.1
=> Update version in package.json to 4.4.1

configs/application/manifest-local.json
Update manifest-local.json with new 4.5 assimilation
=> Update manifest-local.json with new 4.5 assimilation

README.md, configs/application/components.json, configs/application/manifest-local.json, src/components/welcome/welcome.js
=> Links update

package.json, public/configs/other/installer.json
=> Update package.json for 6.3.2

package.json, project.json, public/configs/application/manifest-local.json
=> Release release/8.9.2

package.json, project.json, public/configs/application/manifest-local.json
=> Release release/8.9.3

package.json, project.json, public/configs/application/config.json, public/configs/application/manifest-local.json
Merging 8.10.4 release into master
=> Release release/8.10.4
