InteropIO/finsemble-seed

- src/tutorials/accountDetail/accountDetail.js
This was preventing state restore from working correctly.
> Get initial customer when there is no state, rather than onload

- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
- src-built-in/components/windowTitleBar/src/windowTitleBar.jsx
Window Title bar was not reading config from the component to override global setting setting for showTabs. Fixed by only using global setting if local setting does not exist. Tested with both global false, local true and vice versa.
> #7368 disable tabs per component

- src-built-in/components/userPreferences/src/components/content/Workspaces.jsx
- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
On saveAs, new Workspace, and export, check to see if autosave is enabled. If so, save the workspace before performing the action.
We should consider moving this functionality into the workspaceClient API. For now, the responsibility lies with the UI.
> Save active workspace when saveAs/new/export workspace

- src-built-in/components/assets/css/_toolbar.css
- src-built-in/components/toolbar/src/dynamicToolbar.jsx
Also fixes a react warning (which could potentially lead to rendering errors) in the dynamicToolbar
> Fixes pins with icons not showing titles

- src-built-in/components/userPreferences/src/components/content/General.jsx
- src-built-in/components/userPreferences/src/components/general/Toolbar.jsx
Adds a user preference for selecting which monitor the toolbar appears on. User must restart for it to take effect (and they must restart with the button to ensure that localStorage is available).
> Added a user preference for switching toolbar monitor.

- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
- src-built-in/components/windowTitleBar/src/windowTitleBar.jsx
Scrollbars now appear underneath window title bar (via a css hack built into the windowTitleBar,jsx) *except* when Window Manager.hackScrollbar=false
> 7966 Hack the scrollbar to appear underneath the window title bar.

- src-built-in/components/assets/css/_theme.css
- src-built-in/components/assets/css/_windowTitleBar.css
- src-built-in/components/floatingTitlebar/src/stores/headerStore.js
Kanban Ticket:  https://chartiq.kanbanize.com/ctrl_board/18/cards/7936/details
Reduced the titlebars from 32px to 25px and performed actions to make everything fit nicely. Tested with all the icons we use in Sales Demo and it should work fine. Let me know if there's any tweaks that need to be made.
> 7936 - Make titlebars 25px

- src-built-in/components/userPreferences/src/components/content/Workspaces.jsx
The workspace renaming dialog in user preferences will no longer allow an empty string to be entered
> 8412 Fixes ability to rename Workspaces

- src-built-in/components/toolbar/config.json
Make path to toolbar icon relative rather than absolute.
> Make toolbar icon path relative

- gulpfile.js
Minor change to ensure we detect dev builds via task names like build:dev in addition to dev:fresh and dev
> Better test for dev build

- assets/css/_windowTitleBar.css
Summary:
When a component is scrolled (vertically) the header stops working. The component cannot be dragged, docked, etc.
List branches or versions affected:
To Reproduce:
Make the welcome component short. Scroll. Try dragging.
Requirements:
Specification for fix:
This is caused by a conflict between the scrollbar hack (html.overflowY, body.overflowY) and the chromium hack. New CSS addresses this.
> adjusted CSS to deal with drag/scroll conflict.

- assets/css/_windowTitleBar.css
position:relative on fsbl-header-title fixes this.
> 9180 Tab "Ghost Image" does not display the correct div

- src-built-in/components/windowTitleBar/src/windowTitleBar.jsx
A customer was having an issue with the window title bar buttons becoming unresponsive for certain zoom levels. When I investigated, I found that the drag handle was scaling. The drag handle was scaling because everything outside of FSBLHeader is scaled, and the drag handle was being inserted into the body tag. 
This PR inserts the drag handle inside of the header, with some minor refactoring.
> Insert drag handle inside of FSBLHeader rather than inside body.

- src-built-in/preloads/zoom.js
Zoom was being done using multiplication, but as a result, you could never get back to 100% using the zoom hotkeys. (1 * 1.1 * 0.9 = 0.99). Switching to addition means the zoom and be undone.
> Switched zoom from multiplication to addition

- configs/application/config.json
New config `finsemble.servicesConfig.logger.hotkeyShowCentralLogger` with a default of "ctrl","`". Requires updated Finsemble with matching PR.
> 9351 added hotkey config for central logger

- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
When stacked windows are grouped their icon did not update.  We didn't check for parent and parent windows were't actually being set. To test create a stacked window, group it with some other window and restart. The group icon should come back in the correct state.
https://chartiq.kanbanize.com/ctrl_board/18/cards/9668/details
Also needs this: https://github.com/ChartIQ/finsemble/pull/902
> 9968 make the group icon work when a window has a parent

- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
**Resolves 9875**
- Disallows the use of switchToWorkspace until switchTo is completed.
See card to verify that this fixes the bug.
> 9875 Lock the workspace switching mechanism until the switch is completed

- src-built-in/components/windowTitleBar/src/windowTitleBar.jsx
**Resolves Sales Demo Issue with Salesforce components**
- Prevent second call to injectHeader from breaking the titlebar
> make sure titlebar doesnt get injected multiple times

- src-built-in/components/toolbar/stores/toolbarStore.js
**Resolves 9876**
- On maximized, restore the window. This causes a flash, but doesn't allow the toolbar to take up all of your monitor's space.
- The toolbar doesn't maximize when double clicking the drag handle.
**Card**
https://chartiq.kanbanize.com/ctrl_board/18/cards/9876/details
**Finsemble PR**
https://github.com/ChartIQ/finsemble/pull/928
> 9876 double click toolbar

- src-built-in/components/floatingTitlebar/src/stores/headerStore.js
- src-built-in/components/toolbar/stores/toolbarStore.js
**Resolves 9865**
- Removes unhelpful maximize handler. We used to not trigger bounds-changed events on maximize. Now we do. That code isn't necessary.
- Remove check for whether the window is moving. bounds-change-end doesn't happen if the window is moving.
- Maximize notepad. Verify position.
- Restore notepad. Verify position.
- Minimize notepad. Verify position.
- Restore notepad. Verify position.
> Companion window follows native window on maximize.

- src-built-in/components/toolbar/stores/toolbarStore.js
**Resolves #9908**
- Use getBounds instead of corrupted "window-bounds" in componentState to get bounds
Toolbar doesnt vanish on restart in Finsemble electron
> get proper bounds instead of bad bounds from componentState

- configs/application/config.json
Set to true so that auto-save is disabled - switch it to false to reenable. Whatever our default this should probably be explicit in the config
**Resolves #CS:21**
https://chartiq.kanbanize.com/ctrl_board/21
- Add explicit config
- set to disable auto-save
- Open a workspace, change it, switch to another workspace and you should get prompted to save (rather than it auto-saving)
> [CS: 21] Adding config (already supported) to seed to turn on/off workspace autosave

- src-built-in/components/common/windowTitle.jsx
- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
- src-built-in/components/windowTitleBar/src/windowTitleBar.jsx
Top level component used to listen for title changes and then resize the drag handle. Now the component does it. To trigger the same result, we pass the resize drag handle down into the title component, and invoke it when the title changes. This allows the user to move the window properly.
> Fix drag handle width issues

- configs/application/presentationComponents.json
- src-built-in/components/userPreferences/src/app.jsx
**Resolves #10018**
- Makes User Preferences dialog always on top
1. Open User Preferences dialog
2. Click on scrim
3. User Preferences should remain above the scrim
> Set user preferences to always be on top

- configs/application/config.json
- package.json
**Resolves [9458]()https://chartiq.kanbanize.com/ctrl_board/18/cards/9458/details**
- Moves assimilation config from `betaFeatures` to `servicesConfig`.
- Verify that all config was moved and that only that config was moved.
> 9458 assimilation out of beta

- src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx
- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
**Resolves #10200**
- If no indentifier is present in the dropped data on a tab, ignore it
- Tabbing works as expected (including reordering, native tabs, switching)
- Dropping unexpected items (images, other random text onto tabs) doesnt cause errors. (there will still be the - extractWindowIdentifier error but no others)
** Notes **
The check for dropping on self is purposely missing in floatingTitlebar because the windowName and tab dont match and that check is not needed.
> 10200 ignore non-tab drops

- package.json
Finsemble seed should be tied to a specific version of Finsemble, rather than a name, so when you pull a tagged release, the version is correct.
> Tie finsemble seed with a specific version of Finsemble Core

- src-built-in/adapters/indexedDBAdapter.js
**Resolves #10271**
- return undefined instead of {} when there isn't a value in the IndexedDB
Before https://github.com/ChartIQ/finsemble/pull/961
- Enable indexedDB adapter
- Create new workspace
- Try to switch workspaces (fails before this fix and the above PR)
> 10271 no value should be undefined, rather than an empty object

- configs/application/config.json
- src-built-in/components/appLauncher2/src/components/FoldersList.jsx
- src-built-in/components/appLauncher2/src/components/TagsList.jsx
- src-built-in/components/appLauncher2/src/stores/StoreActions.js
**Resolves issues**
Ticket [10441](https://chartiq.kanbanize.com/ctrl_board/18/cards/10441/details)
Ticket [10443](https://chartiq.kanbanize.com/ctrl_board/18/cards/10443/details)
Ticket [10389](https://chartiq.kanbanize.com/ctrl_board/18/cards/10389/details)
Ticket [10388](https://chartiq.kanbanize.com/ctrl_board/18/cards/10388/details)
- Cancel folder rename on focus remove when no input given
- Save folder name when user click anywhere except rename input
- Restore favorite folder icon
- Persist filter tags list on Finsemble restart
Pull the branch 
> 10442_10443_10389_10388_fixes
, check out and make sure that the above list items are either fixed/enhanced.
> [AppLauncher] Fixes for folder rename, tags list, favorite icon

- assets/css/_theme.css
- src-built-in/components/appCatalog2/src/components/SearchBar.jsx
- src-built-in/components/appLauncher2/src/components/FilterSort.jsx
- src-built-in/components/shared/TagsMenu.jsx
- src-built-in/components/shared/style.css
**Resolves issue [10445](https://chartiq.kanbanize.com/ctrl_board/18/cards/10445/details)**
- Added font icon to tags menu for app catalog and new app launcher that will indicate when a tag is active or not
- Instead of the tags menu simply adding tags, it can now toggle tags. If its already applied and is clicked it will be removed and vice versa
- Verify that you can add a tag in app catalog and app launcher 2. When the tag is added, a check mark is added next to the tag that means its enabled. Clicking any tags with check marks next to them will also remove that tag.
> Fixes tags menu visually indicate what tags are active

- src-built-in/components/appLauncher2/src/components/AppActionsMenu.jsx
- src-built-in/components/appLauncher2/src/components/AppDefinition.jsx
- src-built-in/components/appLauncher2/src/components/AppTagsList.jsx
- src-built-in/components/appLauncher2/src/components/Content.jsx
**Resolves issues**
[10405](https://chartiq.kanbanize.com/ctrl_board/18/cards/10383/subtasks)
[10436](https://chartiq.kanbanize.com/ctrl_board/18/cards/10383/subtasks)
- Apps now launch from a single click on the appLauncher (will not launch apps when the context menu or tags are clicked)
- Tag search is now AND not OR. Only apps containing _all_ currently filtered tags will show
- Confirm that multiple active tags only shows apps that contain all those tags, and that a single click will launch an app
> [AppLauncher] Launch apps with single click, tag filter using AND instead or OR

- src-built-in/components/floatingTitlebar/src/stores/headerStore.js
**Resolves #9652 #9646**
- bringToFront is not called for invisible window
- Open 2+ notepads
- Tab them together
- Move the active notepad a little bit many times to confirm the companion window doesn't disappear
> Companion window for tabbed apps disappear fix

- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
Now we set the `switching` boolean to false inside of `onAsyncComplete`,
which happens after the workspace is switched _or_ the action is cancelled.
**Resolves issue [10637](https://chartiq.kanbanize.com/ctrl_board/18/cards/10637/details)**
-`switching` was only being set to false inside of the `switchTo` callback. This PR changes that to `onAsyncComplete`.
-Move window, switch workspace. Click No. Workspace comes back without changes saved.
-Move window, switch workspace. Click Yes. Workspace comes back with changes saved.
-Move window, switch workspace. Click Cancel. Nothing happens.
-Move window, switch workspace. Switching workspaces is possible.
> 10637 Pressing cancel locks the user out from switching workspaces.

- configs/application/config.json
- src-built-in/components/appCatalog2/src/app.jsx
- src-built-in/components/appLauncher2/src/components/AppActionsMenu.jsx
**Resolves issue [#10407](https://chartiq.kanbanize.com/ctrl_board/18/cards/10407/details)**
- Modified Welcome component id to match one in appd
- Transmit `viewApp` whenever user clicks on `view info`
- Listen for `viewApp` events in appCatalog app.jsx
Open launcher and catalog, open welcome app actions menu and click on `view info`, app catalog should be brought to front and switched to welcome app info page.
> [AppLauncher] [AppCatalog] View app info

- src-built-in/components/appLauncher2/src/components/FoldersList.jsx
- src-built-in/components/appLauncher2/src/components/LeftNav.jsx
**Resolves issue [#10408](https://chartiq.kanbanize.com/ctrl_board/18/cards/10408/details)**
- Disable dragging on my apps and favorites
- Ignoring the reorder if the destination is My apps or Favorites
> [AppLauncher] Disallow My apps and Favorites reorder

- src-built-in/components/linker/src/linker.jsx
**Resolves issue [10021](https://chartiq.kanbanize.com/ctrl_board/18/cards/10021/details)**
- Only call fitToDom when the component is mounted
- The first time the linker is opened, it should be the correct size.
> 10021 Only resize the window when it is mounted

- src-built-in/components/authentication/authentication.js
**Resolves issue [10780](https://chartiq.kanbanize.com/ctrl_board/18/cards/10780/details)**
assimilation.js now uses FSBL.System.getCurrent.show() instead of WindowClient.show()
Added a config entry to turn authentication on:
```
"authentication" : {
"startup" : {
"adapter": "PASSWORD",
"component": "defaultAuthentication"
}
},
```
> 10780 fixed assimilation.js to show() and hide() with new methods.

- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
**Resolves issue [10753](https://chartiq.kanbanize.com/ctrl_board/18/cards/10753/details)**
Removed Logger noise by straightening out use of magic strings in error messages, moving them into constants and fixing mismatches.
- I tested to ensure that you could cancel from any of the following without any errors:
- New Workspace
- New Workspace with Overwrite
- Save As
- Save As with Overwrite
> 10753 remove wsmm noise

- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
**Resolves issue [10781](https://chartiq.kanbanize.com/ctrl_board/18/cards/10781/details)**
- Remove finWindow listener. Change icon state based on finsembleWindows listeners on maximized/restored.
- ALSO NEEDS CORRESPONDING FINSEMBLE PR 
- Double Click Titlebar in Stack. Make sure it maximizes and icons are correct. Double Click again and restore
- Double click Titlebar in Badboy component while render is blocked. Make suremaximize eventually succeeds, as does restore.
> double click to maximize sometimes doesnt work

- configs/openfin/manifest-local.json
- src-built-in/components/appLauncher2/src/stores/StoreActions.js
**Resolves issue [10754](https://chartiq.kanbanize.com/ctrl_board/18/cards/10754/details)**
- When an adhoc component is added, FSBL is called to add the component
- Verify that an adhoc component added at runtime can pin and unpin from the taskbar using the 'favorite' feature
> [AppLauncher] 10754 ability to pin adhoc components

- configs/application/components.json
**Resolves issue [11123](https://chartiq.kanbanize.com/ctrl_board/18/cards/11123/details)**
- nonConfiguredComponent should be marked as a system component and not drop out of config during dynamic config
> 11123 Set category: system on nonConfiguredComponent

- tutorials/accountList/accountList.css
**Resolves issue [10486](https://chartiq.kanbanize.com/ctrl_board/18/cards/10486/details)**
- Added explicit `height` prop to the `relocate` component in `accountList.css` to prevent it from changing height.
- Also bumped `bottom: 0px` to `bottom: 25px` to prevent it from showing up beyond the border of the window on launch.
- Check that the `accountList` component looks ok both at launch and on resize.
> Fixe oozing button in tutorial accountList.css

- src-built-in/adapters/indexedDBAdapter.js
- src-built-in/adapters/localStorageAdapter.js
LocalStorageAdapter updated to standardise its callback use and match logging to IndexedDBAdapter. Fix IndexedDBAdapter exports.
**(Helps) Resolves issue [11497](https://chartiq.kanbanize.com/ctrl_board/18/cards/11497/details)**
-During storage debug for client, standardised the storage adapter implementations and logging. Ensuring that the LocalStorageAdapter provides a better example amnd doesn't include anti-patterns (like retuning success statuses after receiving an error back from a storage op). THese anti-patterns where replicated by client's code.
-Ran finsemble with clear cache and both storage adapters mapped to topics. Confirmed that they successfully completed get and save storage ops and that logging was correct/matched to …
> standardise storage adapter logging and implementations

- src-built-in/components/toolbar/stores/searchStore.js
**Resolves issue [11486](https://chartiq.kanbanize.com/ctrl_board/18/cards/11486/details)**
Using animate function added to DockableWindow. The existing function connected to has fewer parameters.
Requires: https://github.com/ChartIQ/finsemble/pull/1075
Make toolbar small and open and close search bar. Verify no exceptions occur.
> 11486 dockable window animate exception

- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
**Resolves issue [11567](https://chartiq.kanbanize.com/ctrl_board/18/cards/11567/details)**
-Previously we listened for bounds-set events on the finsemble windows.
-Moves to listening on the DOM's resize event.
This works because of the way the underlying container's events are abstracted away from the DOM. Even though the outer rectangle has been resized and an event has been received, the DOM may not have redrawn itself. Because tab sizing depends on the physical pixel size of the items in the DOM, this PR changes the listener from the finsemble window to the DOM window.
-Restored/maximized/resized a couple of stacks of various sizes.
> 11567 listen for DOM resize event to resize the tabs.

- package.json
**Resolves issue [11664](https://chartiq.kanbanize.com/ctrl_board/18/cards/11664/details)**
- Point to e2o 3.7.0 instead of latest.
- Built and ran Finsemble on Electron
> e2o should point to a specific release

- configs/application/presentationComponents.json
- src-built-in/components/toolbar/stores/toolbarStore.js
remove unused functions from toolbarStore
**Resolves issue [11653](https://chartiq.kanbanize.com/ctrl_board/18/cards/11653/details)**
Adds `"canMaximize": false` to the toolbar config.
-How did you verify that your code satisfies the card's requirements?
See https://github.com/ChartIQ/finsemble/pull/1137
> Fix Maximize Toolbar loop

- assets/css/font-finance.css
**Resolves issue [12055](https://chartiq.kanbanize.com/ctrl_board/18/cards/12055/details)**
- Removed data-icon selector from font-finance
- Create an adhoc component at the URL:  https://prd-p-4pl82v44zxvm.cloud.splunk.com/en-US/app/launcher/home
- Spawn the component
- Login using Andy's credentials:
user:  andy_chartiq
pass:  Reach closely creature agree1!
- When main dashboard loads, check to make sure the items in the top navigation Toolbar read "Splunk | Messages | Settings | Activity".  (i.e., they should not appear as jumbles of Finsemble icons).
> 12055 removed data-icon selector

- src-built-in/preloads/zoom.js
**Resolves issue [11624](https://chartiq.kanbanize.com/ctrl_board/18/cards/11624/details)**
-Override OpenFin setZoomLevel function in setup of our preload - reintroduced from old zoom preload in use at JPM
-Added mapping for numeric keypad + key
-Tested zooming with Wlecome component was unaffected by change
> 11624 Disable open fin zoom api

- gulpfile.js
**Resolves issue [11939](https://chartiq.kanbanize.com/ctrl_board/18/cards/11939/details)**
- Added print of e2o version if `channelAdapter` is `e2o` and e2o is installed
- Clean checkout and install
- Run `npm run build` - builds successfully, no e2o output
- Change `channelAdapter` in `config/other/server-environment-startup.json` to `e2o`
- run `npm run build` - Throws error, suggests installing e2o
- Run `npm i @chartiq/e2o`
- Run `npm run build` - Builds successfully, output e2o version
- Change `channelAdapter` in `config/other/server-environment-startup.json` to `openfin`
- run `npm run build` - builds successfully, does not output e2o version
> 11939 Added e2o version check

- gulpfile.js
**Resolves issue [11686](https://chartiq.kanbanize.com/ctrl_board/18/cards/11686/details)**
- Check process.platform, and provide correct command for windows and non-windows
Ran the following tests on OSX and Windows
1. Ran finsemble using `npm run dev`
2. Once finsemble was up, I used Ctrl+C to kill it in the terminal
3. Finsemble closes, no errors in the terminal
4. Ran finsemble again, starts fine, no errors from port in use
> 11686 provide windows and osx kill command

- src-built-in/components/appLauncher/src/stores/appLauncherStore.js
- src-built-in/components/processMonitor/src/stores/ProcessMonitorStore.js
**Resolves issue [11967](https://chartiq.kanbanize.com/ctrl_board/18/cards/11967/details)**
- Altered the dialog buttons for the Terminate Process, Delete App
-Open the Process Monitor and press "Terminate" next to one of the processes. The dialog that appears should have the options "Cancel" and "Terminate"
- Create an adhoc component, then go to the menu and delete it. The dialog that appears should have the options  "Cancel" and "Delete"
> 11967 dialog buttons

- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
**Resolves issue [11878](https://chartiq.kanbanize.com/ctrl_board/18/cards/11878/details)**
- Adjusted workspace dialog buttons so they reflect the actions that will be performed. (It's better UX than labeling them "Yes" or "No".)
1.  Dirty a workspace and perform a workspace switch. Check to see that saving dialog buttons read "Don't Save | Cancel | Save"
2. Choose "Save As" and name a workspace the same as another workspace. The prompting dialog's buttons should read "Cancel | Overwrite"
3. When deleting a workspace, the prompting dialog's buttons should read "Cancel | Delete"
> 11878 workspace dialogs

- configs/application/config.json
- src-built-in/components/appCatalog2/src/stores/storeActions.js
- src-built-in/components/myApps/src/stores/StoreActions.js
**Resolves issue [12053](https://chartiq.kanbanize.com/ctrl_board/18/cards/12053/details)**
* Change FDC3Server to appDendpoint to better reflect what the config means.
* Change code to point to new config property.
**How to test**
1. Clone this repo: https://github.com/ChartIQ/fdc-appd, npm install, and npm run start.
2. Modify the value of `appDirectoryEndpoint` in `configs/application/config.json` to point to the local server. See `//appDendpoint` in the config for instructions.
3. Modify `config.json` in `src-built-in/toolbar` and change `App Launcher` (at the bottom) to `My Apps`.
4. Modify `presentationComponents.json` so that the component named `App Catalog` is named `Not the App Catalog`.
5. Modify `presentationComponents.json` so that the component …
> 12053 change FDC3Server to appDirectoryEndpoint.

- configs/application/securityPolicies.json
**Resolves issue [12332](https://chartiq.kanbanize.com/ctrl_board/18/cards/12332/details)**
Fix naming and misspelling errors in SecurityPolicy.json
-Tested in permissions branch 11995 that the correct permissions were pulled in for an untrusted policy
> Fixed naming and misspelling.

- src-built-in/components/floatingTitlebar/src/app.jsx
- src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx
- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
**Resolves issue [11830](https://chartiq.kanbanize.com/ctrl_board/18/cards/11830/details)**
- Changed data type for tabbing from `"text/plain"` to `"application/fsbl-tab-data"`
- Verify that windows can tab together
- Open application that accepts text drop (I used Notepad++), and drag a tab into the window. Verify that no string is dropped, and window moves to drop location
> 11830 - Changed data type for tabbing from text/plain to custom type

- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
**Resolves issue [12656](https://chartiq.kanbanize.com/ctrl_board/18/cards/12656/details)**
- Removed fixed height from title bar container
- npm run dev
- open an app
- verify that the title bar does not have an extra 20px of space under the title bar
> Removed fixed height on titlebar container

- configs/other/server-environment-startup.json
- gulpfile.js
updating was not put through the ringer. Removes config for updates and changes the warning to info.
> Remove updateURL from config as it is experimental and untested.

- configs/application/config.json
**Resolves issue 12522 ](https://chartiq.kanbanize.com/ctrl_board/18)**
-Changed config to isolate Router Service in its own splintering process 
-Brought up Finsemble and used Process Monitor to confirm Router Service was isolated. 
-Brought up large workspace with debug logging enable and confirm performance was substantially better for logging and toolbar menus (although still a little slower than desired).
> 12522 isolate router service

- src-built-in/components/userPreferences/src/components/content/Workspaces.jsx
fix: #id 12618
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12618/details)
* Removed setting allowDelete false and special deleteTooltip when the active workspace is focused. There is not trashcan icon next to delete, so there is no need to check this and there were issues with this click not triggering a new focused workspace. The special tooltip would only work if it's connected to an onhover event, but is also not needed for the same reason (no trashcan icon).
1. Create two workspaces and open the preferences dialog.
1. Select the active workspace
1. [x] Can hover over workspaces trashcan and see "delete" as the tooltip.
1. [x] Clicking delete over the other workspace pops up the delete dialog after one click and …
> Fix deleting requiring two clicks when active workspace is false.

- configs/application/components.json
- configs/application/presentationComponents.json
- src-built-in/components/processMonitor/src/components/ProcessStatistics.jsx
fix: #id [13055]
Requires fea pr: https://github.com/ChartIQ/finsemble-electron-adapter/pull/84
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13055/details)
* Adds default configuration that enables affinity. Based on this branch: https://github.com/ChartIQ/finsemble-seed/compare/develop...services_as_scripts taking only the affinity-related config changes and making a few naming changes:
- presentationComponents are renamed to systemComponents so they won't show in simple mode of process monitor
- Process monitor is moved from systemComponents to workspaceComponents. Because of a memory leak bug all apps reloaded by a workspace need to be in the same affinity.
See …
> Affinity default configuration

- src-built-in/components/processMonitor/src/components/ProcessStatistics.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12383/details)
Requires: https://github.com/ChartIQ/finsemble-electron-adapter/pull/86
* Fixes pid label for process monitor
See fea pr above.
> fix: #id 12383 Fix pid label for process monitor fix

- tutorials/accountDetail/accountDetail.js
- tutorials/accountList/accountList.js
- tutorials/accountStatement/accountStatement.js
fix|feat|chore|docs|refactor|style|test: #id 13333
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/13333/details/)
* Changes
1. Step 1. Clone seed project
1. Step 2. Create components accountList and accountDetail from the finsemble cli and add files accountList and accountDetail from the tutorial folder to the component folder
1. Step 3. Run the app, and the account list window should show a list of the preset accounts
> fix: 13333 accountList window is not showing any content

- gulpfile.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13097/details)
* Moved Electron existence check to launchElectron 
1. Run `git clean -xfd` and make sure _node_modules_ is deleted
1. Remove `"@chartiq/finsemble-electron-adapter"` entry from `optionalDependencies` in _package.json_
1. Run `npm i`
1. Run `npm run build`
1. [x] Finsemble builds without error
1. Run `npm run dev`
1. [x] Finsemble fails to run with the following error:
`Cannot use electron container unless finsemble-electron-adapter optional dependency is installed. Please run npm i @chartiq/finsemble-electron-adapter`
1. Revert change to _package.json_
1. Run `git clean -xfd`
1. Run `npm i`
1. Run `npm run build`
1. [x] Finsemble builds without errors
1. Run …
> fix: #id [13097] Moved Electron existence check to launchElectron

- gulpfile.js
Same as https://github.com/ChartIQ/finsemble-seed/pull/361 for 3.9
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13097/details)
* Moved Electron existence check to launchElectron 
1. Run `git clean -xfd` and make sure _node_modules_ is deleted
1. Remove `"@chartiq/finsemble-electron-adapter"` entry from `optionalDependencies` in _package.json_
1. Run `npm i`
1. Run `npm run build`
1. [x] Finsemble builds without error
1. Run `npm run dev`
1. [x] Finsemble fails to run with the following error:
`Cannot use electron container unless finsemble-electron-adapter optional dependency is installed. Please run npm i @chartiq/finsemble-electron-adapter`
1. Revert change to _package.json_
1. Run `git clean -xfd`
1. Run `npm i`
1. …
> Moved Electron existence check to launchElectron

- configs/application/presentationComponents.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12742/details)
* Add 'maximizable' property to window options for toolbar. This is passed down to the container and prevents the toolbar from maximizing.
1. Start up in openfin. 
1. Double-click the toolbar -- no maximize.
1. Try to maximize the toolbar by dragging above the monitor -- no maximize.
Do the same in electron. The behavior reported in the card no longer happens.
> fix: #id 12742 Fix Toolbar Maximizing at top of monitor.

- src-built-in/components/processMonitor/src/stores/ProcessMonitorStore.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13539/details)
* Do not show windows for Services when they are clicked on in Process Monitor advanced mode
* Animate does not work in electron, so use show and hide instead.
1. start process monitor. 
1. switch to advanced mode. 
1. Click on a bunch of items in the list
1. [ ] Service windows don't show up. 
1. [ ] Other windows should flash
1. Test in both electron and openfin
> fix: #id 13539 dont show services, hide windows if they were hidden

- src-built-in/components/floatingTitlebar/src/stores/tabbingStore.js
- src-built-in/components/userPreferences/src/components/content/Workspaces.jsx
- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
fix: #id 13489
* This fix preserves backward compatibility with 3.8.x for workspace format. Related to https://github.com/ChartIQ/finsemble/pull/1288
* See https://github.com/ChartIQ/finsemble/pull/1288
> fix: #id 13489 revert change to workspace format

- src-built-in/components/toolbar/components/Search.jsx
- src-built-in/components/toolbar/stores/toolbarStore.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13955/details)
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13956/details)
* Added err to callback so that check for if(err) doesn't fail.
1. Test that pinned items hotkeys (Ctrl + Alt + 1, 2 etc. work)
1. That that Ctrl + Alt + Down Arrow minimizes all (Ctrl + Alt + Up restores all)
> fix: #id 13955 toolbar registered hotkeys not working

- src-built-in/components/toolbar/components/Search.jsx
- src-built-in/components/toolbar/stores/searchStore.js
- src-built-in/components/toolbar/toolbar.css
fix: #id [13493]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13493/details/)
* Remove the range (highlight) of the search text when user click away
* Remove duplicated code
1. Run Finsemble seed
1. Type something in the search bar in the tool bar
1. Select a search result
1. Click into the search bar again and select the search result
1. [x] We can no longer see the highlighted search text
> id: #13493 fix search bar highlighting text on selection

- src-built-in/components/toolbar/components/Search.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13967/details)
* Previously, if one typed in a search, pressed the down arrow, and
pressed enter, the search menu would reappear after launching the component.
This is fixed.
* Changes
1. Type into the seach box 'we'.
1. Press the down arrow.
1. Hit enter.
Observe that the search menu hides and does not reopen.
> fix: #id 13967 Fix search menu hide behavior on enter

- src-built-in/components/appLauncher/src/stores/appLauncherStore.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14035/details)
Test with this finsemble PR: https://github.com/ChartIQ/finsemble/pull/1320
* The app launcher was setting all components to isUserDefined: true, no matter what.
This caused the unknown component to not work, as they aren't used for userDefinedComponents.
1. See steps in the finsemble repo.
> fix: #id 14035 unknown native components

- src-built-in/components/adhocComponentForm/app.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13995/details)
* Call alwaysOnTop on componentDidMount so that the new app menu sits on top of everything else.
1. Click 'my apps'. Open app catalog.
1. Click 'my apps'. Click 'new app'.
1. Observe that the new app form is on top of the app catalog.
> fix: #13995 Prevent app catalog from sitting on top of new app form

- src-built-in/components/userPreferences/src/components/content/Workspaces.jsx
fix: #id13977
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13977/details)
* Removed unnecessary `this.cancelEdit()` from `setWorkspaceList()`
- Checkout this branch 
- Launch finsemble `npm run dev`
- Open user preferences > workspaces
> fix: #13977 Edit workspaces name in preferences

- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
fix: #id [14145]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14145/details)
* Added `removeFromWorkspace: true` to the close of `closeTab` in the UI.
1. Tab a notepad onto a welcome component.
1. Activate the welcome component tab.
1. Close the notepad tab.
1. Reload the workspace.
1. [x] The workspace reloads succesfully
> Add removeFromWorkspace true to closeTab

- src-built-in/components/floatingTitlebar/src/stores/tabbingStore.js
fix: #14222
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14222/details)
When the floating title bar (i.e companion window) closeTab is invoked, then close the window with the parameter set to remove it from the workspace.  This closeTab function is invoked when a notepad window's tab is closed within a stacked window.   
1. change the seed config to run on OpenFin
1. create a stacked window of five notepads.
1. close each of the tabs, one by one (in different orders, alternating active and inactive tab).
1. Then reload the workspace
Do the same test above three times until 1) no windows are left, 2) one window is left (without a stacked window), 3) and two windows are left (i.e. the stacked window with two tabs). …
> Floating titlebar fix

- assets/css/_toolbar.css
Addresses comments in https://github.com/ChartIQ/finsemble/pull/1065
It also has its own card: https://chartiq.kanbanize.com/ctrl_board/18/cards/11529/details
-Changed position of `.resize-handle` to `absolute`, with `right: 0` to make it always stay flush with the end of the toolbar.
-Added a slight margin to right section of the toolbar buttons so they retain the original spacing (since `absolute` isn't counted in spacing).
- Checked to see that the toolbar still looked normal at various sizes.
> 11529 resize toolbar vertically

- src-built-in/components/toolbar/stores/searchStore.js
This applies back the emptying of the list and hiding of the search
results window when a user is done searching.
The removal was introduced in a bad merge of 3.10.0 into the original PR
branch.
fix: [14494](https://chartiq.kanbanize.com/ctrl_board/18/cards/14494/details/)
1. Run Finsemble
1. Open the search box in the toolbar
1. Search for something like "We"
1. Click out onto the desktop to remove focus from the search input
1. [x] EXPECT the search results window to close
1. Open the search box again
1. Focus the search input for typing and see the results window
1. Press `esc`
1. [x] EXPECT the search results window to close with the input
1. Open the search box again
1. Select the Welcome Component entry
1. [x] EXPECT the search results window to close with …
> fix: search store for toolbar not closing the results window

- build/webpack/webpack.components.js
- package.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14653/details)
* changed webpack.component.js to recursively search for finsemble.webpack.json
1. Check out sales demo planned/3.10.0
1. cd in finsemble-seed and validate the branch for this ticket is the seed branch
1. cd back to sales demo root
1. run `npm i`
1. run `npm run build`
1. Compare _dist/components/authentication/authentication.js_ with the file in _src_ and _src-built-in_
1. [x] Validate that the output file was built from _src_ version.
> fix: 14653 fix recrusive find

- src-built-in/components/myApps/src/stores/StoreActions.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14621/details)
* components created in the favorites folder get pinned
1. Go to favorites folder.
1. Add new app.
1. Observe app added to toolbar.
1. Go to custom folder.
1. Add new app.
1. Observe app not added to toolbar.
> fix: #id 14621 components created in the favorites folder get pinned

- src-built-in/components/myApps/src/utils/sort-functions.js
fix #id [14761]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14761/details)
Fixing the sort function for the app launcher menu.
1. Enable the new app launcher in the toolbar config
1. Replace components.json with this file: https://drive.google.com/file/d/19ssaktqO4y0aRFgWcdtTFD3ZpDq0otRj/view
1. Load Finsemble with clean storage
1. Open the My Apps menu
1. Add some components to Favorites.
1. Select sorting by "Alphabetic".
1. Confirm that, when "Alphabetic" sorting is selected, the components are sorted by name alphabetically.
1. Select sorting by "Favorites".
1. Confirm that, when "Favorites" sorting is selected, the components are sorted by whether they are in favorites (favorites come first) and then by name …
> 14761-sort-of-app-launcher-results-failing

- src-built-in/components/myApps/src/components/FoldersList.jsx
Fix #id [14694]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14694/details)
* Track mouse Y position
* Move folder to the top/bottom of list based on mouseUp position
1. Check out this branch and switch to new app launcher `My Apps`
2. Start fresh and create 3-4 folders
3. Drag a folder from center or bottom all the way to the top or top outside the window
4. Drag a folder from center or top all the way to the bottom or bottom outside the window
`NOTE: When dragging the folder away from the window and releasing it, it will first return to where it was and then get to the top or bottom of the list, a limitation in current HTML5 drag and drop`
See screenshot for expected results.
> Fix #14694 When a folder dragged over "My Apps" or "Favorites" move to the top of the list

- package.json
- src-built-in/components/appLauncher/src/stores/appLauncherStore.js
- src-built-in/components/toolbar/modules/pinManager.ts
- src-built-in/components/toolbar/stores/toolbarStore.js
- tsconfig.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14688/details)
This PR makes it so that pins are renamed when the underlying component has a display name change. Additionally, if the component is removed from components.json, the pin will be excluded from the toolbar.
This PR also fixes tsconfig and ts-loader issue I had while working.
1. Load Finsemble on planned/3.10.0.  Pin a workspace and every component that is loaded. Switch to this branch and run `npm install`.
2. In components.json, change the component:displayName of Welcome Component to some other name.
3. In components.json, remove the Notepad entry.
4. Restart Finsemble.
5. Confirm that the pin for the Welcome Component has changed its name to whatever you …
> fix: #id 14688 app cant unpin when name changes

- assets/css/_windowTitleBar.css
- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
- src-built-in/components/windowTitleBar/src/components/center/logo.jsx
- src-built-in/components/windowTitleBar/src/components/center/tab.jsx
The logo code for tabs has been broken for quite a while.
Upon triaging it to get them back, all kinds of weird state
isolation problems were appearing.
It was decided that rather than address all of this now in 3.x
we will remove what functionality was left of it for this series.
For the ux refresh in 4.x this will be revisited and brought back
in a properly functioning way.
To account for the logo element no longer being in the DOM, which
was giving some space in between the divider and title. We now
have a fixed padding of 8px on the left of the title text.
This prevents the text from directly touching the divider visually.
https://chartiq.kanbanize.com/ctrl_board/18/cards/14738/details/
Do keep the Central Logger open and set to "Errors only" to verify along …
> chore: remove icon support from window tabs

- build/webpack/webpack.components.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14765/details)
* Added regex replaces to change all \\ to /
1. Use the sales demo develop branch
1. check out the branch for this PR in the finsemble-seed submodule
1. Commit branch change to temporary branch (so install doesn't revert the change)
1. In the sales demo run `npm i`, then
1. `npm run build`
1. Examine files in the sales demo with _finsemble.webpack.json_ to verify that imports/requires are resolved by webpack.
> fix: #id 14765 Forced webpack config to use / instead of \\

- src-built-in/components/linker/src/linker.jsx
fix: #id [13862]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/13862/details)
Because the OS and container maintain separate records of which window has focus, they were getting out of sync in the case of WPF windows and the Linker Window, causing the Linker to stick around after the WPF window regained focus (according to Windows). To fix this, we added the notion of a "remote focus" event, whereby assimilation and WPF can signal to Finsemble via listen/transmit that a window outside of Finsemble's knowledge has received focus. When this happens, Finsemble blurs whichever window last had focus (we rely on the existing mechanisms to focus the correct window).
- Added new "focused" state to OpenFinWindow class that toggles as the window is …
> 13862 - Added manual focus to linker window on show

- src-built-in/components/appCatalog2/src/app.jsx
- src-built-in/components/myApps/src/index.jsx
fix: #13686 [CARD]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/13686/details/)
**Description of change** event handler added to appCatalog2 to check when finsemble was fully loaded. MyApps event handlers for ready function formatting cleaned up.
1. Step 1. Change the following from "App Catalog" to "App Catalog old" https://github.com/ChartIQ/finsemble-seed/blob/13686-initialise-on-fsbl-ready/configs/application/presentationComponents.json#L718
1. Step 2. Change the following from "App Catalog 2" to "App Catalog" https://github.com/ChartIQ/finsemble-seed/blob/13686-initialise-on-fsbl-ready/configs/application/presentationComponents.json#L758
1. Step 3. Run the app and click on "Apps --> …
> Fix #13686 FSBLReady event listened for to bootstrap components.

- src-built-in/components/toolbar/stores/toolbarStore.js
fix: #14675 [CARD]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14675/details)
* Changes blurred state write to storage instead of workspace (component state)
1. Paired with core branch: https://github.com/ChartIQ/finsemble/pull/1382
1. Run finsemble
1. Ensure toolbar is claiming space (assuming default config)
1. Undock and move toolbar, restart
1. [ ] Toolbar restored in previous place
1. Redock then restart
1. The toolbar should still be claiming space on restart
1. [ ] Space was correctly claimed
> 14675 Change write to component state to storage

- src-built-in/components/linker/linker.html
fix: #id 14897
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14897/details/)
Changed linker window name in HTML so that assimilation name for window in focus event matches container name for window (Brad identified this anomaly).  
*Test on OpenFin Container*
1. Bring up multiple welcome components
1. Click on linker icon to bring up linker window in each.  The linker window should stay up as long as it maintains focus (i.e. until click outside of linker window).
> Change Linker Window name

- src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx
- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
fix: #id [14562]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14562/details)
**Get  proper bounding rect on drag stop**
* Previously, the code for stopDrag was using the "options" for the window component and not getting the actual bounding box for the current component state. Code was updated to use the getBounds() method for returning the bounding box.
Code for blank component in components.json:
```
"BlankComponent": {
"window": {
"url": "https://finsemble.chartiq.com/components/system/blankComponent/index.html",
"width": 660,
"height": 410
},
"component": {
"mode": "premium",
"category": "system"
},
"foreign": {
"services": {
"dockingService": {
"isArrangable": true
}
},
"components": {
"App Launcher": {
"launchableByUser": true
},
"Toolbar": {
"iconClass": …
```
> 14562 Cross domain breaks tabbing

- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
fix: #id 14144
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14144/details/)
* spawnDialog is expecting a callback as the third parameter, pass in the function prototype as callback since we don't need to log anything for the user input in this case.
1. Pull down this branch, test along with planned/3.11.0
1. Create a workspace and click "save as", when the dialog prompt up for you to name the workspace, don't put in anything and click "confirm"
1. [x] Notice the logger will have the "invalid workspace name" error(which is useful and we want to keep that one) but no "userinput is not a function" error
> fix: #id 14144 workspace save without user input causes logger error

- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14047/details)
* Fixes onTitleChanged function which is supposed to update the title in array of tabs, but was instead removing other tabs from the array.
To test in regular finsemble:
1. Start finsemble and stack two process monitor components
1. With the left tab focused, open the devtools for that tab and run 'FSBL.Clients.WindowClient.setWindowTitle('fake')'
1. [x] Click on the non-focused tab, it should switch tabs as expected
To test in Sales-Demo (where the reported bug actually happens):
This very hard, we want to find a better way, but currently there is a bug in seed affecting the build of sales demo so this is the only way right now.
Setup:
1. Pull down the …
> fix: #id [14047] tab changing issues in sales demo

- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
fix #id [14689]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/14689/CARD/details)
We need to ensure that the key attribute in React components is unique to that component and will not change.  This helps React determine whether to update the DOM or not.
The error that was observed in central logger was a result of the incorrect tab(s) being updated because the key was the index in the list of tabs, which caused React to think that a tab that had been moved did not need to be re-rendered when in fact it did, and that a tab that had not been moved needed to be re-rendered when it fact it did not.
Given the right sequence of actions, this resulted in componentWillUnmount being called on a component which had not received a componentWillMount call, hence …
> 14689-Dragging-a-tab-can-cause-central-logger-erro

- src-built-in/components/windowTitleBar/src/components/right/AutoHide.jsx
- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
recipe: #id [13795]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/13795/details/)
* Only suspend the auto hide on drag if the component has it enabled.
1. Open 3 welcome components
1. Set auto hide to off on one and on on the other
1. [x] AutoHide works according to the setting set on the respective windows
1. Tab the 3rd component into one of the other
1. [x] AutoHide still works according to the setting set on the respective windows 
1. Untab the component
1. Open 3 welcome components
1. Set auto hide to off on one and on on the other
1. [x] AutoHide works according to the setting set on the respective windows
1. Tab the 3rd component into one of the other
1. [x] AutoHide still works according to the setting set on …
> Auto-hiding window chrome bug

- src-built-in/components/windowTitleBar/src/components/right/AutoHide.jsx
- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
+ only suspending autoHide when it's enabled on the component.
recipe: #id [13795]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/13795/details/)
* Filled in the blanks
* Only suspend the auto hide on drag if the component has it enabled.
1. Open 3 welcome components
1. Set auto hide to off on one and on on the other
1. [x] AutoHide works according to the setting set on the respective windows
1. Tab the 3rd component into one of the other
1. [x] AutoHide still works according to the setting set on the respective windows 
1. Untab the component
1. Open 3 welcome components
1. Set auto hide to off on one and on on the other
1. [x] AutoHide works according to the setting set on the respective windows
1. Tab the 3rd …
> Filling in the blanks for AutoHide 

- package.json
- src-built-in/components/myApps/src/stores/StoreActions.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15127/details)
* Catch exception when thrown during access of non existing `launchableByUser`
1. Check out this branch run `npm run dev`
1. Editing toolbar/config.json line 50 set menuType to `My Apps`
1. Edit components.json remove `foreign` key from Welcome Component
1. Run the seed `npm run dev`
> Fix 15127 My Apps is vulnerable to components with invalid config

- src-built-in/components/toolbar/stores/toolbarStore.js
fix: #id 14699, 14619, 14479
Three related tickets are addressed by this PR since the code was interrelated. Suggest all three tickets be reviewed at once.
See corresponding finsemble branch of same name.
Kanban for 14699
Kanban for 14619
Kanban for 14479
Description of Change
All monitor related code was deleted from toolbar and moved into Docking in window service.
> 14699 toolbar visibility moved to window service

- src-built-in/components/toolbar/stores/toolbarStore.js
fix: #id [15475]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15475/details)
**Changed hotkey handler to "bringToolbarToFront"**
* Previous hotkey handler activated the search box but did not bring toolbar to front. This call has been updated.
1. Run finsemble
1. Put finsemble toolbar behind a native window. (Explorer, chrome, etc...)
1. Press Ctrl + Alt + F
1. [ ] Toolbar is properly brought to front over non-finsemble windows.
> 15475 - Toolbar bringtofront on hotkey

- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
fix: #id [14512]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14512/details)
**TilingStop on Tabbing Cancel**
* The core PR fixes the drop targets. However, MikeM discovered that we still had issues when dropping on the titlebar. When we start tabbing, the drag handle gets hidden. This code update will have the titlebar listen for the cancel event as well as the stop event so that the drag handle will be unhidden and the window can be moved again after we cancel tiling or tabbing.
1. Run finsemble with both PR's.
1. For this one, drop the tab back on it's own titlebar, or itself and make sure the window is still draggable afterwards.
> 14512 TilingStop on tabbing cancel

- server/server.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16247/details)
* Changed the path of the error check to the correct path of the new System Manager
1. The timeout error no longer appears when starting Finsemble
> fix: #id 16247 Spurious Service manager timeout error in console

- configs/application/config.json
fix: #id [15814]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15814/details)
Removes unused properties from docking service configuration.
1. Boot the finsemble seed project. Ensure that there are no new errors in the central logger.
> 15814 remove docking default height

- src-built-in/components/linker/src/linker.jsx
- src-built-in/components/windowTitleBar/src/components/left/LinkerGroups.jsx
fix|feat|chore|docs|refactor|style|test: #id [16401]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16401/details)
* Changed "Group" to "Channel" in the accessible linker.
1. Open the Linker
1. See that it reads "Channel 1" and not "Group 1".
1. Assign a color channel.
1. Hover over the color on the titlebar and see that the tooltip reads "Channel 1"
> 16401 Change Group to Channel

- gulpfile.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/14743/details)
* Added log message containing the container name (Electron/OpenFin)
1. Edit `server-environment-startup.json`
1. Set `container` to `Electron` and run `npm run dev`
1. Set `container` to `OpenFin`  and run `npm run dev`
> [14743] Print out container name in console

- gulpfile.js
feat: #id [16424 ]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16424/details)
* Read Electron version from package.json
* Read OpenFin version with hadouken
* Print out container version next to its name
1. Checkout this branch
1. Set container to (electron/openfin) and run `npm run dev`
Look for container name and version in logs printed out in green color.
> [16424] read and print out OpenFin/Electron version

- src-built-in/components/floatingTitlebar/src/components/TabRegion.jsx
fix: #id [11790]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/11790/details)
* Add check and cancel tabbing when necessary
This issue is happening when there is a single tab only. When you drag the component title and drop it on itself the component will freeze, you won't be able to move it around anymore and you won't be able to resize it. See gif below
To test the fix
1. Please checkout planned/3.13.0 and experience the bug
1. Check out this branch and run finsemble `npm run dev`
1. Launch a Notepad
1. Expand floating titlebar and drag the title and drop it on itself
1. Collapse floating titlebar and Try moving notepad/resizing it
> [11790] Native component freeze/breaks when tabbing on self

- src-built-in/components/myApps/src/stores/StoreActions.js
fix: #id 16706
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16706/details/)
* After the apps are loaded from the config, delete the apps inside the "App" menu folders so that the apps in the folders match the component config
1. Test this branch along with Finsemble core and FEA on planned/3.13.0 branch
1. Update finsemble-seed -> src-built-in -> components -> toolbar -> config.json to use the "My app" menu instead of "App Launcher" menu
1. Launch finsemble, create 1 or 2 new folders, add several components (i.e. welcome component and notepad) to the "favorite" folder and the new folders you created.
1. Go to finsemble -seed -> configs -> application -> …
> fix: #id 16706 update my apps folders to match the components config setting

- src-built-in/components/floatingTitlebar/src/stores/headerStore.js
When the event handler was removed in 45771b5498bf861e7388191499102faed73b83ce the binding of it was not removed.
This removes the binding, so an undefined handler is no longer bound.
fix: #16759
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16759/details)
Maximize a native window on OpenFin that has a floating titlebar (like Notepad.) Observe no errors in the Central Logger from that action.
> fix: floating titlebar maximize error

- package.json
- src-built-in/components/toolbar/src/app.jsx
- src-built-in/components/toolbar/stores/toolbarStore.js
feat: #id [12600](https://chartiq.kanbanize.com/ctrl_board/18/cards/12600/details/)
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/12600/details)
* Adds a close confirmation dialog when a user right clicks to close finsemble toolbar. Previously there was no dialog, and choosing close would close the toolbar (with no way of getting it back). 
1. Checkout `planned/4.0.0` in `finsemble` and `finsemble-electron-adapter`
2. Checkout `12600-toolbar-close-confirm` in `finsemble-seed`
3. Launch finsemble
4. Right click the left hand side of the finsemble toolbar
5. Choose close
6. A dialog should appear. Test both cases.
-> Clicking cancel should do nothing
-> Clicking Shut down should should down finsemble
> Set up close request confirmation dialog when user right clicks to close finsemble toolbar

- configs/application/manifest-local.json
Small Tweak -- This is a PR without a ticket.  Kyle found old name was used while creating new startup test cases.  
* In the 4.0 seed I updated the config example to use new name (i.e. task instead of module).
> 4.0 Startup-Config Tweak (no affect on runtime)

- src-built-in/components/toolbar/components/DragHandle.jsx
- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
feat: #id 16932 to 16935
**Note**: 4 cards' work is combined into 1 PR because we couldn't test the code effectively if it's broken down one by one.
[Kanban link 1](https://chartiq.kanbanize.com/ctrl_board/18/cards/16932/details/)
[Kanban link 2](https://chartiq.kanbanize.com/ctrl_board/18/cards/16933/details/)
[Kanban link 3](https://chartiq.kanbanize.com/ctrl_board/18/cards/16934/details/)
[Kanban link 4](https://chartiq.kanbanize.com/ctrl_board/18/cards/16935/details/)
* Change onmousedown and onmouseup event handler names
Testing details described in https://github.com/ChartIQ/finsemble-electron-adapter/pull/162
> feat: #id 16932 to 16935 onmousedown onmouseup event handler naming change

- gulpfile.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/17132/details)
* Added validation for max node version being 10.15.3 (can be changed in the gulpfile). If validation fails an error will be logged but finsemble will still start.
* Did not use npm engines because it has a bug where the version warning doesn't log prior to npm version 6.12.0
To test without changing npm versions:
1. Note your node version, if <= 10.15.3, start finsemble and verify there are no errors in the terminal above the launching Finsemble line.
2. In the finsemble-seed gulpfile.js change MAX_NODE_VERSION to a version below your current node version
3. Launch finsemble, verify finsemble launches …
> feat: #id 17132 validate max node version

- configs/application/manifest-local.json
fix: #id 16324
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16324/details/)
* Configure the router transport through "router" instead of "IAC" according to the documentation to avoid confusion
Detailed description is described in https://github.com/ChartIQ/finsemble/pull/1588
> fix: #id 16324 manifest router config

- src-built-in/components/myApps/src/components/AppDefinition.jsx
fix: #id 18161
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/18161/details/)
* Always spawn components with a componentType. The original bug happens because we're spawning quick components without setting componentType, which is causing launcher.js to spawn it as an unknownComponent
1. Build and start finsemble
1. Create a quick component
1. Save the quick component in the workspace
1. [x] Reload the workspace and make sure the quick components comes up with the correct webcontent (instead of as an unknownComponent)
1. [x] Restart finsemble and make sure the quick components comes up with the correct webcontent (instead of as an unknownComponent)
1. [x] Other components are also spawned correctly
> fix: #id 18161 spawn quick components with the correct config

- src-built-in/components/myApps/src/components/AddNewAppForm.jsx
URLs were being validated with a buggy regex expression for valid URLs.
This changes the validation to use the URL constructor for simplicity and robustness.
fix: #id [18357](https://chartiq.kanbanize.com/ctrl_board/18/cards/18357/details/)
Followed test instructions in card's referenced test case failure.
> fix: app url validation

- src-built-in/components/toolbar/components/AutoArrange.jsx
fix: #id [18061]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/18061/details)
* Adds logic to properly manage toolbar's representation of auto arrange
Check this out in tandem with core branch: https://github.com/ChartIQ/finsemble/pull/1594
1. https://chartiq.spiraservice.net/3/TestCase/58.aspx
1. https://chartiq.spiraservice.net/3/TestCase/1113.aspx
1. https://chartiq.spiraservice.net/3/TestCase/1114.aspx
1. https://chartiq.spiraservice.net/3/TestCase/1115.aspx
1. https://chartiq.spiraservice.net/3/TestCase/1116.aspx
1. https://chartiq.spiraservice.net/3/TestCase/61.aspx
1. https://chartiq.spiraservice.net/3/TestCase/60.aspx
1. https://chartiq.spiraservice.net/3/TestCase/49.aspx
1. …
> 18061 Reset arranged status on toolbar move

- src-built-in/components/toolbar/src/app.jsx
fix: #id [18316]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/18316/details)
* Remove OF specific hack to reset finWindow bounds on window ready.
1. Undock toolbar from primary monitor and move to another monitor docked or undocked
1. Restart ~10 times and ensure the toolbar restarts in the same location it was left
1. [ ] Toolbar returned to saved location
> fix #id: 18316 Remove OpenFin specific bounds hack

- configs/application/manifest-local.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/18866/details)
* Added FinsembleTransport Config Back in for native components
1. Checkout matching Finsemble branch.
1. Add a WPF Component (must use planned/4.0.0 for finsemble-dll)
1. Run Finsemble and WPF Components should work.
> fix: #id 18866 Added FinsembleTransport Config Back in for native components

- src-built-in/components/toolbar/components/Search.jsx
fix: #id 18518
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/18518/details)
* Delayed closing on search results menu
1. Checkout this branch and run `npm run dev`
1. Add a new component `Google` and URL `http://google.com`
1. Search for Google in toolbar
> [18518] Fix search results not spawned when clicked on

- gulpfile.js
fix: #id 16510
Refer to https://github.com/ChartIQ/finsemble-electron-adapter/pull/171 for details
> fix: #id 16510 fix cross component header value issue caused by applications sharing the same cache folder

- src-built-in/components/myApps/src/components/AppDefinition.jsx
- src-built-in/components/myApps/src/stores/StoreActions.js
fix: #id [18351]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/18351/details)
Link with: https://github.com/ChartIQ/finsemble-react-controls/pull/28
* Added `displayName` to the list of app config items that are pulled into the app launchers store
* Components with no `displayName` property will just use their regular name
* Everywhere where a component's name is displayed, it will instead use the displayName
1. Change `componentName.component.displayName` of some of the components to something other than what it currently is/different than the app's actual name
1. Confirm the 'My Apps' section displays the display name.
1. Favorite the app and confirm the pin name is the display name
1. Confirm the favorites folder …
> 18351 display name in my apps

- src-built-in/components/toolbar/components/DragHandle.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19410/details)
* Add startMovingWindow and stopMovingWindow API methods to the windowClient.
1. Start finsemble.
2. Move windows around quickly.
3. Move windows around slowly.
> chore: #id 19410 Remove reliance on fin API and call the Finsemble API instead

- gulpfile.js
- src-built-in/components/appLauncher/src/stores/appLauncherStore.js
- src-built-in/preloads/nativeOverrides.js
chore: #id [19169]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19169/details)
* Removed app launcher's implementation of launcherGroups
Finsemble PR required to test: https://github.com/ChartIQ/finsemble/pull/1642
1. Add a `launcherGroups` property to two different component's `<name>.component` field, make the value of `launcherGroups` the same for both components.
1. Launch Finsemble
1. Launch both apps and ensure no grouping/simultaneous launching occurs
1. Make sure there is no entry in the `App Launcher` or `My Apps` menu
1. [ ] Everything behaves normally and nothing unexpected was added to the app menus
> chore: #id 19169 Remove implementation of launchGroups in app launcher

- src-built-in/components/windowTitleBar/src/components/left/LinkerGroups.jsx
- src-built-in/components/windowTitleBar/src/components/right/BringSuiteToFront.jsx
- src-built-in/components/windowTitleBar/src/components/right/DockingButton.jsx
- src-built-in/components/windowTitleBar/src/stores/windowTitleBarStore.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19170/details)
* Removed all code in the seed that called or implemented hyperfocus
1. Verified Finsemble starts
1. Verified shift-clicking on a channel no longer triggers the hyperfocus action (all other windows in a different channel minimize). It may still be treated the same as a regular left-click.
> feat: #id 19170 disable hyperfocus

- src-built-in/components/userPreferences/src/components/content/Workspaces.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19029/details)
* Hid the import/export workspace buttons
1. Ran Finsemble
1. Verified import/export workspace buttons were not present
> feat #id 19029 disable import export workspace by default

- src-built-in/components/appCatalog2/src/components/Hero.jsx
- src-built-in/components/appCatalog2/src/components/SearchBar.jsx
fix: #id [19477]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19477/details)
* If number of apps is less than 2 or greater than 10 don't show the pagination bubbles on the Hero component for App Catalog
1. Pull down PR
1. In `src-built-in/components/myApps/src/index.jsx` change `openMarketApp`'s call to LauncherClient.showWindow to launch `App Launcher2` instead of `App Launcher`
1. Check out the local appd: …
> Fix pagination bubbles. Limit to 10, if more than 10 apps, don't show.

- src-built-in/components/appCatalog2/appCatalog.css
- src-built-in/components/appCatalog2/src/app.jsx
- src-built-in/components/appCatalog2/src/stores/storeActions.js
feat: #id [19190]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19190/details)
* Adds generic server error message when appd server responds with an error
1. Pull down PR
1. In `src-built-in/components/myApps/src/index.jsx` change `openMarketApp`'s call to LauncherClient.showWindow to launch `App Launcher2` instead of `App Launcher`
1. Before running the …
> chore: #id 19190 Add generic server error message

- src-built-in/components/toolbar/components/AutoArrange.jsx
- src-built-in/components/toolbar/components/BringToFront.jsx
fix #id 19168
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19168/details/)
* Disable/Hide auto-arrange icon to disable auto arrange, but kept it easy to re-enable since used in testing large workspaces
Confirmed auto-arrange icon is no longer visible (when AutoArrangeEnabled = false);
> 19168 disable auto arrange

- src-built-in/components/appCatalog2/src/components/Toast.jsx
fix: #id 19504
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19504/details/)
* Change the user facing messages when the user adds or removes an app from app catalog
1. Launch finsemble with app catalog configured: https://app.getguru.com/card/i8gLqdpT/Setting-Up-App-Catalog?q=app%20catalog
2. Add or remove an app from the showcase, verify the messages changed to the one described in the card
> fix: #id 19504 change app catalog user facing messages

- src-built-in/components/appCatalog2/src/components/SearchBar.jsx
- src-built-in/components/appCatalog2/src/stores/storeActions.js
fix: #id [19469]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19469/details)
* When text is cleared but tags are still active, the search results are repopulated
1. Pull down PR
1. In `src-built-in/components/myApps/src/index.jsx` change `openMarketApp`'s call to LauncherClient.showWindow to launch `App Catalog2` instead of `App Catalog`
1. Run `npm i`
1. …
> Changes to research tags when active tag search combo with text search

- src-built-in/components/appCatalog2/src/app.jsx
- src-built-in/components/appCatalog2/src/components/AppCard.jsx
- src-built-in/components/appCatalog2/src/components/Showcase/Header.jsx
- src-built-in/components/appCatalog2/src/stores/storeActions.js
fix: #id [19461]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19461/details)
* Fixed app status building to simplify loop and reduce delay which solved the added/removed status issue
1. In `src-built-in/components/myApps/src/index.jsx` change `openMarketApp`'s call to LauncherClient.showWindow to launch `App Catalog2` instead of `App Catalog`
1. Run `npm …
> 19461 add remove app status not updating

- src-built-in/components/appCatalog2/appCatalog.css
- src-built-in/components/appCatalog2/src/app.jsx
refactor: #id [19189]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19189/details)
* Adds error message to app catalog when appd server returns no results
1. Pull down PR
1. In `src-built-in/components/myApps/src/index.jsx` change `openMarketApp`'s call to LauncherClient.showWindow to launch `App Launcher2` instead of `App Launcher`
1. Before running the …
> Add server error message for when appd returns no results

- src-built-in/components/appCatalog2/src/stores/storeActions.js
fix: #id [19424]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19424/details)
* When adding an app, if it has a friendlyName, apply that to the appConfig.displayName that's passed to the launcher
1. In `src-built-in/components/myApps/src/index.jsx` change `openMarketApp`'s call to LauncherClient.showWindow to launch `App Catalog2` instead of `App Catalog` …
> Add fdc3 app's friendlyName as component displayName

- src-built-in/components/appCatalog/src/stores/searchStore.js
- src-built-in/components/toolbar/config.json
feat: #id 19507
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19507/details)
* Set default menuType to "App Launcher" in toolbar config
* Fix bug with searchStore where finWindow is undefined
1. Checkout this branch and run `npm run dev`
1. Navigate to toolbar > Apps
> feat #id 19507 Make the basic App Catalog the Default for Finsemble

- configs/application/UIComponents.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19354/details)
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19058/details)
* Pieces of the toolbar's config never made it from 3.x to 4.x. I brought over existing config.
1. Ensure toolbar can't be snapped to.
1. Ensure toolbar can't be grouped with.
1. Ensure toolbar can't be tiled onto.
1. Ensure WC can be tiled onto.
1. Ensure WC can be tabbed onto.
1. Ensure WC can be grouped with.
> fix: #id 19354 Toolbar config is incorrect; toolbar can group and be tiled onto.

- src-built-in/components/myApps/src/components/AppActionsMenu.jsx
- src-built-in/components/myApps/src/components/SearchBox.jsx
fix: #id [16680]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/16680/details)
* Use window's on blur event instead of finsembleWindow's blurred
1. Checkout this branch, and edit toolbar's component config.json
1. Set `menuType` to `My Apps`
1. Start finsemble `npm run dev`
1. Click on Apps to open app catalog then click on the 3 vertical dots next to each app to toggle the menu`
1. [ ] Make sure that `Add to favorites` menu item does not hides/blink regardless of how many time you try
> [16680]  Fix "Add to Favorites" menu item closes/flickers without user input

- configs/application/components.json
- configs/application/config.json
fix: #id 20022
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/20022/details)
* set tabbing and tiling to false by default
1. Start Finsemble
2. Spawn two Welcome components
> 20022 disable tabbing and tiling by default

- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
fix|feat|chore|docs|refactor|style|test: #id [CARD]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15321/details/)
* Removed UI restriction that prevents switching workspace before the previous switch is complete. 
See corresponding Finsemble PR: https://github.com/ChartIQ/finsemble/pull/1610  --  **These two PRs must used and merged together.**
> 15321 workspace failures

- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
- src-built-in/components/advancedAppLauncher/src/index.jsx
fix: #id [19920]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19920/details)
* The code undergirding pins needs work. This bug came down to some nuance in how components are registered and how their configs are updated. Essentially the Process Monitor was registering as a 'nonConfiguredComponent'; and that's where its pin was going (the 2nd time...the first time, the system couldn't distinguish between this one and the one installed initially). 
So when you'd try to remove the 'process monitor' pin, noting would happen. Only the 'nonConfiguredComponent' would be pinned.
This PR changes component registration so that apps registered via the advanced app catalog register with a component type and do not end up saved as 'nonConfiguredComponent'. …
> fix: #id 19920 Fix a bug where components installed via the advanced app launcher did so incorrectly

- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
fix: #id [19852]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19852/details)
* Created an drop event handler for non tab areas in titlebar.
* Stop event propagation when tab is dropped on another tab.
1. Create 2-3 welcome components
1. Tab all components
1. Drag any tab and drop it on an empty area in title bar
1. [x] Shouldn't loose window control
1. [x] Should see a blue scrim when hovering on windows
See the following card to see what the bug looks like
https://chartiq.kanbanize.com/ctrl_board/18/cards/14562/details/
> [19852] Fix: window control lost when dropping tabs

- src-built-in/components/advancedAppCatalog/src/components/SearchBar.jsx
- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
fix: #id [19915]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19915/details)
* Set proper callbacks for the search field clean event
Setup https://app.getguru.com/card/i8gLqdpT/Setting-Up-Advanced-App-Catalog
1) Open Advanced App Catalog
2) Type Notepad in the Search field
3) Remove Notepad from the Search field
4) Type Notepad in the Search field
5) Click **x** to clean the search field
> 19915 Fix clean search field issue

- gulpfile.js
We support 12.13.1, this updates the max version to reflect this.
> chore: update max supported node version

- src-built-in/components/advancedAppLauncher/src/components/Content.jsx
fix: #id [20449]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/20449/details)
**Removed reference to dashboards in Advanced App Launcher**
* Changed empty favorites string
1. Open Advanced App Launcher
1. Open an empty favorites folder
1. Verify that the text says: "There’s nothing here! Add apps to Favorites to view them here."
> 20449 Remove reference to dashboards

- src-built-in/components/windowTitleBar/src/windowTitleBarComponent.jsx
feat: #id [19350]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19350/details)
* Add a double click handler
1. Checkout this branch and run `npm run dev`
1. Spawn a welcome component and double click on titlebar
1. [x] Window maximizes
1. Double click again
1. [x] Window restores
> feat: #id 19350 Maximize/Restore on double click

- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
fix: #id [20480]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/20480/details)
**Prevent duplicate tags in Advanced App Catalog**
* Added a check so we don't get duplicate values in tags
1. Set up advanced app catalog: https://app.getguru.com/card/i8gLqdpT/Setting-Up-Advanced-App-Catalog?q=app%20catalog
1. In the Catalog, choose a tag. (App) In the now filtered carousel, click the same tag on the card.
1. App is only shown as a selected tag once.
> 20480 Prevent duplicate tags in Adv App Catalog

- src-built-in/components/windowTitleBar/src/components/left/LinkerGroups.jsx
fix: #id [20467]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/20467/details)
* Added 'accessibleLinker' to component state for proper initialization; moved it out of global file state
1. Add two components to workspace and link them to a channel
1. Reload the saved workspace
1. [ ] windowTitleBar of reloaded windows should have properly styled linker pill (little rounded corner square with a number inside of it)
> Add 'accessibleLinker' to component state for proper initialization

- src-built-in/components/advancedAppCatalog/src/app.jsx
- src-built-in/components/advancedAppCatalog/src/components/SearchBar.jsx
- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
fix: #id [20921]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/20921/details)
**Cleaned up state/store logic for App Catalog**
We had several listeners that were copying data to and from state. When we moved the state data into store for combinatory searching, we (I) introduced some timing issues with those listeners.
* ActiveApp, filteredApps, activeTags... Are all moved to central store entirely. We should not be relying on copies of these in state.
* Listeners have been cleaned up to prevent the exchange of local state to store. 
* Helpers have been added to get store values for UI instead of relying on state data.
1. Build this branch with Advanced App catalog: https://app.getguru.com/card/i8gLqdpT/Setting-Up-Advanced-App-Catalog
1. Verify …
> 20921 app catalog back button

- src-built-in/components/advancedAppCatalog/src/app.jsx
fix: #id [20921]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/20921/details)
**Set forceSearch earlier**
* In some cases, searching and then clicking on an app card would not open the showcase. Moving the forceSearch to an earlier point in the code to help.
1. Open AAC
1. Search using text only
1. Click on an app card
1. Showcase opens.
> 20921 set forceSearch earlier

- src-built-in/components/advancedAppLauncher/src/components/FilterSort.jsx
fix: #id [19910]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19910/details)
* FilterSort section of launcher now listens for app changes
* When an app is added or removed, the launcher's tags are recalculated and the UI is updated
1. Set up the app to use the advanced app launcher and advanced app catalog
1. Run finsemble and open the app launcher > app catalog
1. Add an app by clicking the check, or the 'Add' button on the app showcase
1. The tags list presented in the app launcher should update with tags from the added app
1. [ ] Tags list updated when an app is added
1. Remove the app and make sure the tags list is updated
1. [ ] Tags list updates when app is removed
> fix: #id 19910 Update launcher tags when app is added or removed

- configs/other/installer.json
fix: #id 19998
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19998/details/)
See https://github.com/ChartIQ/finsemble-electron-adapter/pull/182 for details
> fix: #id 19998 Add comments to specify what characters are allowed in the installer name

- configs/application/components.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/19305/details/)
**Fix Welcome component and other example configs**
* The seed project contained some config options that were not working as they were not in the correct place (e.g. window.autoShow, which should be window.options.autoShow). This misleads clients all the time - particularly as we don't document window.options (we used to rely on OpenFin for this).
1. Run the seed project and check the Welcome component is working as normal.
1. Change some of the window.options.* settings (e.g. set `window.options.resizable = false` or `window.options.alwaysOnTop = true`) 
1. Restart Finsemble and see that the specified settings apply to the component correctly.
> fix: #id [19305] correct window.options in seed components

- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
fix: #id [21548]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/21548/details)
* Parse manifest from FDC3. If parsing of string fails, try and fetch from the string. If that response fails, prevent adding the app and throw an error
1. Setup app catalog
1. Seed with missing manifests/bad manifests
1. Start Finsemble
1. Try to add an app with a bad or unresolvable manifest
1. [ ] App does not add, and Finsemble throws an error
> fix: #id 21548 App catalog not parsing manifest from FDC3

- package.json
feat: #id [21021]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/21021/details)
* Finsemle CLI dependency version updated to the latest 3.13.0
n/a
> 21021 Finsemble CLI version update to 3.13.0

- tsconfig.json
feat: #id [19152]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/19152/details)
- Adds type declaration files to the seed.
- Modifies the tsconfig.json to work correctly.
Ideally, we shouldn't need to do this - VS Code/Typescript should infer the types from the "types" prop of Finsemble's package.json. However, I could not get that to work after several days of trying.
- Build and launch finsemble
- Launch one of each: stack of group welcome components, notepad, welcome component.
- Reload the workspace.
> 19152 Add types to seed

- assets/css/_toolbar.css
- src-built-in/components/toolbar/src/app.jsx
- src-built-in/components/welcome/welcome.html
feat: #id [22719]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22719/details)
* Created a new reusable react component `ToolbarSection`
* Added definition for ResizeObserver
1. Checkout finsemble-ui@22719ToolbarResponsiveness
1. `npm run dev` in both seed and ui
1. Resize toolbar to the minimum/maximum
The middle section where favorites are, should render when middle section is > 115px and should not render when its less than 115px. This number can be configured in `toolbar/src/app.jsx`
```jsx
<ToolbarSection className="center" minWidth={115}>
```
When  > 155px
https://app.zeplin.io/project/5a6b7dea31e01cd724fc9f60/screen/5e431d42bb5b28b3f8b762fa
When <= 115px …
> 22719 toolbar responsiveness

- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
fix: #id [22639]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22639/details)
* Remove folder prop from `registerComponent`
1. Grab https://github.com/ChartIQ/fdc-appd and run `npm start`
1. Checkout seed@`22639-appacatalog-addapp`
1. Line 155 in seed config.json `"appDirectoryEndpoint": "http://localhost:3030/v1",`
1. Edit seed `src-built-in/components/toolbar/config.json` and set `menuType` to `Advanced App Launcher`
1. Edit seed `src-built-in\components\advancedAppLauncher\src\components\LeftNavBottomLinks.jsx` and uncomment line 8
1. Run seed `npm run dev-fresh`
1. Create a folder in the Advanced App Launcher
2. Open the Advanced App Catalog
3. Add an app to the Launcher using the Check mark icon on the app card.
> fix: #id 22639 Don't add app to current custom folder

- src-built-in/components/advancedAppCatalog/src/components/Showcase/Header.jsx
- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
- src-built-in/components/appLauncher/src/stores/appLauncherStore.js
fix: #id [22923]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22923/details)
**Moved load of AAC components to Startup**
* Components will be added to the Workspace when the "Open" button is clicked on their AAC page.
* SearchLauncher "listener" has been changed to a PubSub.
* Registration of components has been moved to Core instead of Seed.
1. Run Finsemble
1. Add a Sample Component to a Workspace via AAC.
1. Reload Finsemble and verify Sample Component
1. Verify that Sample Component is available via Toolbar Search.
1. No additional Central Logger Errors or Warnings that are not required were introduced by this PR
> 22923 aac load components

- src-built-in/components/authentication/authentication.js
fix: #20886 [CARD]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/20886 /details)
* Improve comments in example only
No significant code change.
1. Enable authentication as per the auth tutorial: https://documentation.chartiq.com/finsemble/tutorial-Authentication.html
1. check that auth component shows up on launch and then allows finsemble to complete startup once the user logs in
> 20886 improve authentication example comments

- configs/application/UIComponents.json
fix: #id 22271
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22271/details/)
* Took out depreciated toolbar config
* Set the "autoShow" flag inside the toolbar config to be true in case user set the workspaceService.global to be false (currently undocumented). In that case if we have autoShow set to be false, the toolbar would come up hidden.
1. Launch finsemble
1. Make sure toolbar shows up and cannot tab, tile, nor snap
> fix: #id 22271 Take out depreciated toolbar config

- src-built-in/components/advancedAppCatalog/appCatalog.css
- src-built-in/components/advancedAppCatalog/src/components/Hero.jsx
fix|feat|chore|docs|refactor|style|test: #id [21743]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/21743/details)
* In the Advanced App Catalog, the hero component has been restructured so the text is no longer lying on top of the image.
* The image is now scaled and in full view. 
* App descriptions longer than 5 lines get truncated.
1. Enable the Advanced App Catalog, [help here](https://github.com/ChartIQ/finsemble-manual-testing).
1. Open the Advanced App Catalog.
1. Ensure that the text in the hero component sits to the left of the image.
1. Ensure the image in the hero component is scaled and not cut off.
> 21743 Hero Component redo

- src-built-in/components/singleInputDialog/src/app.jsx
refactor: #id [22728]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22728/details)
Adds a SingleInputDialog component, copied from the seed project.
I verified each of the requirements in the below doc, using the New Workspace dialog as the test case.
https://docs.google.com/document/d/1SV-JIC7D1WxtLHIVxieaB4SB7c1nod5JXMe6MkGYt7o/edit
> use exported component

- src-built-in/preloads/zoom.js
feat: #id [21061]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/48/cards/21061/details)
* Add support for default zoom config setting at `foreign.components.['Window Manager'].zoomDefault` in the component config
1. Edit the Welcome Component config and set `foreign.components.['Window Manager'].zoomDefault = 0.5`
1. Spawn the Welcome component and check that it is zoomed out to 50%
1. change the zoom level and save into a workspace
1. reload the workspace and ensure that the zoom level is preserved in state in preference to default zoom level
> 21061 add defaults to zoom preload

- src-built-in/components/advancedAppLauncher/src/components/AppDefinition.jsx
- src-built-in/components/advancedAppLauncher/style.css
Fix padding on tags.
Make grays consistent.
Reduce brightness of tag icon.
Remove hardcoded 'gray'
> fix: 23161 fix tags styling on adv app launcher

- src-built-in/components/authentication/Authentication.jsx
chore: #id 23340
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/23340/details/)
* Change the import path of the useAuth hook
1. Modify the finsemble config to use authentication. Test along with https://github.com/ChartIQ/finsemble-ui/pull/36
1. Launch finsemble, make sure the authentication window shows up with no error in the console.
> chore: #id 23340 Change the import path of the useAuth hook

- configs/application/components.json
fix: #id 24432
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/24432/details/)
* Default to not show AOT button for Welcome Component
1. Launch finsemble and make sure the welcome component's titlebar does not have the always on top icon
> fix: #id 24432 Default to not show AOT button for Welcome Component

- src-built-in/components/advancedAppCatalog/appCatalog.css
- src-built-in/components/advancedAppCatalog/src/components/AppCard.jsx
fix: #id [22626]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/22626/details)
* Adds another css class for when a checkmark is already active and gets hovered
* Added code to the AppCard to change the css state of the check depending on the state of installation and hover
1. Setup Finsemble and the advanced app launcher/catalog
1. Install an app
1. From a catalog screen containing app cards, notice the active checkmark (green to indicate installed). Hover over it and notice the change in green (subtle difference between light green and a darker green)
1. [ ] Hover state of active checkmark changed on hover
> fix: #id 22626 Hover colors on active check need color differentiation

- build/webpack/defaultWebpackConfig.js
- build/webpack/webpack.titleBar.js
- build/webpack/webpack.vendor.js
…ebar (thats where the error was)
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/15542/details)
* Makes webpack builds consistently use define plugin instead of a mix of define and environment plugin.
* Adds mode to titlebar (that's where the error was).
1. Ran seed. Opened a couple components. No errors.
> fix: Fix bug with redux complaining about NODE_ENV being set improperly

- src-built-in/preloads/zoom.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/25157/details)
* Changed the zoom preload to try to read the zoom config from the component config first
* If not present in component config, read the global config
1. Added zoom config to the Welcome Component config and made sure it applied.
1. Removed zoom config from the Welcome Component and moved to the global "Window Manager" config and made sure it applied.
```
"zoom": {
"timeout": 4000,
"step": 0.15,
"min": 0.7,
"max": 1.0
}
```
> fix: #id 25157 zoom preload should read component config zoom settings

- src-built-in/components/advancedAppLauncher/src/index.jsx
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/23320/details)
* Fixes an issue where advanced app launcher search persisted on restart. This is a port of the same fix in 5.0 from https://github.com/ChartIQ/finsemble-ui/pull/43. However, only a small amount of that fix is needed as the new menu portal structure in 5.0 changes how menus work. That fix also changed the behavior of search so that the results cleared on app selection. In 5.0, both toolbar search and advanced launcher search have that behavior. As toolbar search still maintains state on app launch in 4.3 that change was also not pulled into this fix to keep the behavior consistent.
* Clears the filtertext value in the store on launch, this value is used to populate the search results. …
> fix: #id 23320 advanced app launcher search no longer persists on restart

- src-built-in/components/advancedAppLauncher/style.css
* In Advanced App Launcher, if a tag was added to the search, the searchClear 'x' would shift downwards. This prevents that from happening.
1. Enable Advanced App Launcher
1. Put some text into the search.
1. Add a tag to the search.
1. See if the 'X" switches position up or down...it shouldn't.
> Fix position of searchClear 'x'

- src-built-in/components/linker/src/stores/linkerStore.js
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/25633/details)
* Call FitToDOM each time the window shows to account for new channels.
See companion finsemble PR - 
https://github.com/ChartIQ/finsemble/pull/1894
> fix: #id 25633 new Channels don't show up

- gulpfile.js
feat: #id [25360]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/25360/details)
* Installer builder checks env variable for cert passphrase
**Required PRs**
Finsemble: https://github.com/ChartIQ/finsemble/pull/1887
FEA: https://github.com/ChartIQ/finsemble-electron-adapter/pull/234
1. Provide a cert file in the installer.json
1. Build an installer with `INSTALLER_CERTIFICATE_PASSPHRASE=***** npm run makeInstaller:prod` where **** is the password to the  provided certificate
1. [ ] Installer built with certification
> feat: #id 25360  Change makeInstaller task to check for cert password on env

- src-built-in/components/advancedAppCatalog/src/components/Showcase/AppShowcase.jsx
fix: #id [21949]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/21949/details)
* Passes entire app from Showcase to Header to allow name or title access
1. Open Finsemble with Advanced App Launcher and Advanced App Catalog enabled
1. Start example fdc-appd server with json from ticket: https://chartiq.kanbanize.com/ctrl_board/106/cards/21949/details/
1. Add and open the only app in the provided json. Launch from the app catalog
1. [ ] App should launch without issues
> fix: #id 21949 21949 aal title bug

- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
- src-built-in/components/advancedAppCatalog/src/utils/helpers.js
- src-built-in/components/advancedAppLauncher/src/components/AppDefinition.jsx
- src-built-in/components/advancedAppLauncher/src/components/Content.jsx
- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
- src-built-in/components/advancedAppLauncher/src/utils/helpers.js
- src-built-in/components/advancedAppLauncher/src/utils/sort-functions.js
fix: #id [26156]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/26156/details)
* Changes how apps inside folders are read in due to changes in the  underlying data structure
1. Setup Finsemble with Advanced App Launcher
1. Favorite an app
1. Ensure the app appears on the  toolbar and the star is filled in
1. Clicking to favorite again should do the opposite
> Fix favorites folder display/apps calculation

- src-built-in/components/advancedAppCatalog/src/components/Showcase/Header.jsx
- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
- src-built-in/components/advancedAppCatalog/src/utils/helpers.js
- src-built-in/components/advancedAppLauncher/src/utils/helpers.js
fix: #id [26161]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/26161/details)
* Fix errors in catalog and launcher helpers trying to access folder data
* Don't add catalog added app to active launcher folder
1. Run Finsemble with Advanced App Laucher and Advanced App Catalog
1. Highlight any folder in the launcher other than the main 'App Launcher' folder
1. Add and app from the catalog's  showcase page
1. [ ] App did not appear  in highlighted folder and was only added to the main folder
> fix: #id 26161 Fix helper issues and don't add catalog app to activeFolder

- src-built-in/components/advancedAppLauncher/src/components/FoldersList.jsx
fix: #id [25683]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/25683/details)
* When a user submits a rename of a folder the new text is checked against the old folder name. If the values are equal the rename is not submitted
1. Run Finsemble configured with Advanced App Launcher
1. Create a custom folder with any name
1. Rename the folder. In the input, type in the same name the folder had before the rename
1. [ ] Folder name returned when submitted and a "(1)" was not appended
> fix: #id 25683 Don't submit rename if newName is same as oldName

- src-built-in/components/advancedAppCatalog/appCatalog.css
fix: #id [26141]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/26141/details)
* Center css content inside of showcase button
1. Run Finsemble with  Advanced App Launcher and Advanced App Catalog
1. Open an app's  showcase
1. [ ] Ensure the 'Add' button has equal spacing on either side inside the button
> fix: #id 26141 Fix styling of add button on app showcase page in advanced app catalog

- build/webpack/defaultWebpackConfig.js
- build/webpack/webpack.preloads.js
- build/webpack/webpack.services.js
- package.json
- tsconfig.json
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/106/cards/25995/details/)
Added the ability to build typescript files when using preload and services from src
* Changes
- Webpack configs changed and tsconfig added react for tsx
- updated typscript dependency to latest (3.9.3)
- Create a typescript service, it should build correctly in the dist folder.
- Create a typescript preload, add it to the preloads.entries file and it should build correctly to the dist folder. 
- Try the above with JSX - preloads should build
> feat: #id 25975 additional typescript support

- src-built-in/components/advancedAppCatalog/src/components/Showcase/Header.jsx
fix: #id [26172]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/26172/details)
* When an app is launched from the catalog and it isn't a url based component, always launch using the apps name, never the title.
1. Launch Finsemble configured with Advanced App Launcher and Advanced App Catalog
1. Add an app from the catalog
1. Launch the app using the newly appeared 'Open' button
1. Kill the appd server
1. Restart finsemble, saving the desktop
1. When finsemble restarts, the app added/started from the app catalog should still launch without any problems
1. [ ] App continued to launch after restarts without appd server running
> fix: #id 26172 26172 fix launch from catalog

- src-built-in/components/appLauncher/src/stores/appLauncherStore.js
Prevents App Launcher Startup Error
* if settings are null, log a warning and initialize with empty struct to prevent error
> fix: suprious error in seed

- src-built-in/components/advancedAppLauncher/src/components/FoldersList.jsx
- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
- src-built-in/components/advancedAppLauncher/style.css
fix: #id [25678]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/25678/details)
* Changes how folder order is maintained
* Keeps focus on invalid name inputs and prevents user from editing other folders until conflicts are resolved
* Adds an animation to input to indicate error
1. Start Finsemble with Advanced App Launcher enabled
1. Add a folder
1. Rename the folder to some text that is invalid like "@@"
1. Try to take focus off the input/submit. The input bottom border should flash red to indicate invalid input
1. [ ] Unable to edit other folders/unable to stop editing a folder in error
> fix: #id 25678 Flash input when folder name is invalid. Fix folder reordering issues

- src-built-in/components/advancedAppLauncher/src/components/FoldersList.jsx
fix: #id [24086]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/24086/details)
* Checks for ability to edit before exposing input for folder renaming
* Removed unneeded check for folder icon
1. Add custom folder with foundation that can be edited
1. Click edit icon of configured folder and ensure editing begins
1. [ ] Custom foundation added folder can be edited
> Allow editing of folders with any icon and correct permissions

- src-built-in/components/advancedAppCatalog/src/components/Showcase/Header.jsx
- src-built-in/components/advancedAppCatalog/src/stores/storeActions.js
- src-built-in/components/advancedAppLauncher/src/components/AppDefinition.jsx
- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
fix: #id [21949]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/21949/details)
* Trims names so no extra spaces through  off adding/launching of apps
* Ensures component loading completes in all cases (error or success)
1. Install an app from the advanced app catalog
1. Add the app to the workspace
1. Kill the server
1. Restart Finsemble - the app will load as an 'unconfigured component' because the information could not be loaded from the server
1. Restart the appd server and restart finsemble
1. Windows should reload
1. [ ] Windows loaded unconfigured when server was down and returned when server was back up
> fix: #id 21949 Fixes to FDC3 apps re-registering at startup

- configs/application/config.json
- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
fix: #id [26676]
fix: #id [26681]
[26672](https://chartiq.kanbanize.com/ctrl_board/18/cards/26676/details)
[26681](https://chartiq.kanbanize.com/ctrl_board/18/cards/26681/details)
* Adds `canDelete` to components created with quick add form
* If renamed folder is active folder, resets activeFolder
1. Run Finsemble with Advanced App Launcher
1. Create a custom folder and click on it so the view for the new folder is selected. Rename the folder.
1. [ ] Renaming the folder doesn't cause any errors
1. Restart Finsemble and  ensure the launcher continues to open without errors
1. [ ] Can be restarted after editing a folder name
1. Add a quick component using the built in form
1. [ ] Quick component can be deleted using the context menu
> fix: #id 26676 26681 fixes for app launcher

- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
fix: #id [27837]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/27837/details)
* Checks for folder[folderName].apps instances that are still typeof === "object" and converts them to arrays.
* If a conversion takes place, a Central Logger warning is logged, and a user notification is alerted
1. Run Finsemble 4.2 with the advanced app launcher and add some folders with some apps in them
1. Upgrade to 4.3 without clearing state
1. [ ] The launcher should come up, and Finsemble should throw an alert warning that the data structure is incorrect
1. [ ] The warning will only show once unless the distributed store is set to reseed on every run, until the foundation is fixed, the warning will be received everytime
> Aal new structure transform

- src-built-in/components/userPreferences/src/app.jsx
- src-built-in/components/userPreferences/src/stores/UserPreferencesStore.jsx
- src-built-in/components/workspaceManagementMenu/src/components/workspaceList.jsx
- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
fix: #id [27392]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/27392/details)
* Updates preferences components whenever the view changes to get most up-to-date workspace information
* Removes the constant workspace updates for every action slowing UI down
* Adds a private method to WorkspaceClient to retrieve a list of workspace names
* Adds a method to WorkspaceClient to retrieve the publish update constants to be used by a front end component to potentially filter out constant updates
* Switches name lists over to new method to retrieve workspace names
1. Open the preferences component after enabling import/export
1. Make changes to workspaces using the Preferences component/workspace menu and ensure changes are …
> fix: #id 27392 Fix workspace menu issues regarding updates

- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
Fixes an issue of calling to update folders and providing a parameter that will cause a type mismatch.
> Fix central logger error

- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
* SaveAs was incorrectly checking for existing workspaces
1. Attempted to save workspace as the name of an existing workspace
1. Prompt appears to overwrite
> fix: #id 28354 fix saveas prompt

- src-built-in/components/appLauncher/src/stores/appLauncherStore.js
* assigned setting to empty object if it was undefined.
1. No error in central logger at startup
1. App Launcher still works
see - https://github.com/ChartIQ/finsemble-seed/pull/700
> fix startup error in app launcher

- src-built-in/components/fileMenu/src/stores/fileMenuStore.js
- src-built-in/components/workspaceManagementMenu/src/stores/workspaceManagementMenuStore.js
https://cosaic.kanbanize.com/ctrl_board/106/cards/28431/details/
* use workspaceclient.isWorkspaceDirty() because the isDirty property is no longer valid.
1. Spawn a few HTML components
1. Save workspace
1. Reload should not prompt
1. Add a window to the workspace
1. Reload should prompt to save
1. Add a window to the workspace and close it
1. Reload should not prompt
1. Move a window
1. Reload should prompt to save
> fix: #id 28431 - Refactor of Dirty State

- src-built-in/components/windowTitleBar/src/components/center/TabRegion.jsx
…egion
fix: #id [28710]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/28710/details)
* Adds a pixel to the determined drop zone to determine if the pixel is dropped in the _actual_ tab region or not
1. Drag a tab a single pixel above its tab region to recieve a mouse icon indicating a disabled drop (circle with cross through it)
1. Drop the tab in this area
1. [ ] Ensure Finsemble doesn't get 'stuck' in tiling/tabbing mode and tabs can still be moved around/mousing over other windows does not show a scrim
> 28710 tabbing tiling bug

- src-built-in/components/advancedAppLauncher/src/stores/StoreActions.js
fix: #id [28956]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/28956/details)
* Manually added 'quick apps' convert ids to strings
1. Manually add an app to the Advanced App Launcher using the "New Component" button
1. Drag the app into some folders
1. Restart finsemble and attempt to open the AAL
1. [ ] Menu opened without errors
> fix: #id 28956 Add apps with string id

- configs/application/manifest-local.json
refactor: #id [29253]
[Kanban link](https://chartiq.kanbanize.com/ctrl_board/18/cards/29253/details)
* Added manifest variable: `finsemble-electron-adapter.disableZoom`, moving it out of FEA's window webPreferences
1. Test with FEA PR: https://github.com/ChartIQ/finsemble-electron-adapter/pull/282 and follow the testing steps
> Move electron 'disableZoom' to manifest

- src-built-in/components/linker/src/stores/linkerStore.js
https://cosaic.kanbanize.com/ctrl_board/106/cards/29519/details/
* move fittodom call to after the window is shown
1. Arrange two windows like this: 
1. Alternately hit the linker button on both 50 times
1. Linker window always shows up on the correct window
> fix: #id 29519 Linker sometimes shows up at wrong position
